<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'countries','action'=>'add'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'countries','action'=>'add'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Continents</h3></div>
	<div class="content-box-content">
	
		<div>

			<div class="action-header">
				<span class="action-title">Edit Continent</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br  clear="all"/>
			
			<form id="form-edit-language" method="post" onsubmit="return validate_edit_language('form-edit-language');">
				
				<table class="table-form" cellpadding="0" cellspacing="0">
					<tr>
						<td width="20%" class="tdrightBold">Continent<span class="required">*</span> : </td>
						<td>
							<input type="text" name="continent" id="continent" value="<?php if(isset($formData['continent'])){echo $formData['continent'];}?>" class="req form-textfield"  message="Please enter continent"  invalidmessage="Please enter valid continent"/>
							<?php if(array_key_exists('continent',$formErrors)){echo '<div class="inline-error">'.$formErrors['continent'].'</div>';}?>
						</td>
					</tr>
					
					<tr>
						<td width="20%" class="tdrightBold">Status : </td>
						<td>
							<input type="radio" name="status" value="1" <?php if(isset($formData['status']) && $formData['status']==1)echo'checked="checked"';?>>Active
							&nbsp;&nbsp;
							<input type="radio" name="status" value="0" <?php if(isset($formData['status']) && $formData['status']==0)echo'checked="checked"';?>>Inactive
						</td>
					</tr>
					<tr>
						<td width="20%" class="tdrightBold">&nbsp;</td>
						<td>
							<input type="submit" value="Update" class="button-Add" title="Update" />
							<input type="button" value="Cancel" name="btnCancel" class="button-cancel" onclick="window.location.href='<?php echo $cancelUrl;?>';" title="Cancel"/>
						</td>
					</tr>
				 </table>
			</form>
	</div>
</div>

<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">

function validate_edit_language(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>
<?php /************END JAVASCRIPT CODE**************/?>