<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Currencies</h3></div>
	<div class="content-box-content">	
		<div>
			<div class="action-header">
				<span class="action-title">Currency List</span>
				<ul class="horizonal-menu">
					<li class="add"><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'stores','action'=>'addcurrency'),'',true);?>" title="Add Currency">Add Currency</a></li>
				</ul>
			</div>			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>			
			<br style="clear: both;"/>			
			<table class="table-list" cellpadding="0" cellspacing="0">
			<tr>
				   <th width="5%">Sr.No</th>
				   <th width="5%">ID</th>
				   <th width="20%">Currency Name</th>
				   <th width="10%">Symbol</th>
                   <th width="10%">Action</th>
			</tr>
			
			<?php 
			  if(isset($this->currencyList) && count($this->currencyList)>0)
			  {
				$sNumber=1;
				for($i=0;$i<count($this->currencyList);$i++)
				{
					
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $this->currencyList[$i]['currency_id'];?></td> 
					   <td><?php echo $this->currencyList[$i]['currency_name'];?></td>	
					   <td><?php echo $this->currencyList[$i]['currency_sign'];?></td> 				   
					   <td>
					   
							<a class="action-icon" title="Edit" href="<?php echo $this->url(array('module'=>'admin','controller'=>'stores','action'=>'editcurrency','id'=>$this->currencyList[$i]['currency_id']),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
							
							<!--a class="action-icon" title="Delete" href="<?php echo $this->url(array('module'=>'admin','controller'=>'stores','action'=>'delete','id'=>$row->id),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a-->
							
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="8">&nbsp;</td></tr>';
						echo '<tr><td colspan="8">'.$this->paginationControl($this->countryList,'Sliding','pagination.phtml').'</td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>