<?php
$productHistory = $this->tempOrderData;
?>
<style>
#shipping_record
	{
    display: none;
    height: auto;
    left: 50%;
    margin-left: -50px;
    margin-top: -90px;
    min-height: 50px;
    overflow-x: hidden;
    overflow-y: auto;
    padding: 10px;
    position: fixed;
    top: 50%;
    width: 50px;
    z-index: 1000;
}
.overdelay {
    background: none repeat scroll 0 0 #000000;
    height: 100%;
    left: 0;
    opacity: 0.8;
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 100;
}
</style>
<section id="middle">
<div id="overdelay" class="overdelay" style="display:none;"></div>
<!--cart section start -->
<div class="cart" id="cardId">
<?php
echo $this->datahistory;
?>
</div>
<!--cart section start end -->
</section>

 <div id="shipping_record" style="display:none;" ><img src='<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/loader.gif'/>
       	
</div>