<?php
$formData=(isset($this->formData))?$this->formData:array();

$backUrl=$this->url(array('module'=>'admin','controller'=>'publications','action'=>'index'),'',true);
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Publication Management</h3></div>
	<div class="content-box-content">
	
		<div>

			<br style="clear: both;"/>
			<div class="action-header">
				<span class="action-title">Publication List >> <?php echo $this->ParentBrandInfo['brand'];?>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
				</ul>
				</span>
			</div>
			<br style="clear: both;"/>	
			
			<form id="form-search" method="post" onsubmit="return validate_search('form-search');">
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Publications</th>
				</tr>
				
				 <tr>
					<td width="100%" colspan="8">Title:<input type="text" name="searchword" id="searchword" value="<?php if(isset($formData["searchword"]) && !empty($formData["searchword"])) echo $formData["searchword"]; ?>" style="width:120px;"> Edition:
					<?php
					$editionList = $this->modelEditon->getList(0);
					?>
					<select name="edition" id="edition" style="width:200px;">
					<option value="">Select Edition</option>
					<?php
					for($ii=0;$ii<count($editionList);$ii++)
					{
					?>
					<option value="<?php echo $editionList[$ii]['id']; ?>" <?php if(isset($formData["edition"]) && $formData["edition"]==$editionList[$ii]["id"]){ ?> selected <?php } ?> ><?php echo $editionList[$ii]['edition']; ?></option>
					<?php
					}
					?>	
					</select>
					Status:
					<select name="status" id="status" style="width:120px;">
					<option value="">Select Status</option>
					<option value="1" <?php if(isset($formData["status"]) && $formData["status"]=='1')echo"selected";?>>Active</option>
					<option value="0" <?php if(isset($formData["status"]) && $formData["status"]=='0')echo"selected";?>>Inactive</option>
					</select>
					
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add" title="Search">
					<input type="button" name="showall" value="Show All" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'issues','parentid'=>$this->ParentPublicationInfo['id']),'',true);?>'" title="Show All"/>
					</td>
				</tr>
				</table>
			 </form>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			<br style="clear: both;"/>	
			<table class="table-list" cellpadding="0" cellspacing="0">
			   <tr>
				   <th>SL.No</th>
				   <!--<th>ID</th>-->
				   <th>Title</th>
				   <th>Genre</th>
				   <th>Type</th>
				   <th>Edition</th>
				   <th>Issue Date</th>
				   <th>Status</th>
				   <th style="width:80px;">Action</th>
			   </tr>
			<?php 
			  if(isset($this->issueList) && count($this->issueList)>0)
			  {
				$sNumber=1;
				foreach($this->issueList as $row)
				{
				
				?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <!--<td><?php echo $row->id;?></td>--> 
					   <td><?php echo $row->title; ?></td>
					   <td>
					   <?php
					   $genreInfo=$this->modelGenre->getGenreInfo($row->product_type);
					   echo $genreInfo['genre'];
					   ?>
					   </td>
					   <td>
					   <?php
					   $categoryDetails=$this->modelIssue->getCategoryInfo($row->cat_id);
					   echo $categoryDetails['category_name'];
					   ?>
					   </td>	   
					   <td>
					   <?php
					   $editionInfo = $this->modelEditon->fetchRow("id='$row->edition_id'");
					   echo $editionInfo['edition'];
					   ?>
					   </td>
					   <td><?php echo CommonFunctions::formatDate($row->publish_time); ?></td>
					   <td>
						<?php 
							if($row->admin_approve=='1')
							{
							?>
							<a class="action-icon" title="Active" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'inactive','id'=>$row->id),'',true);?>"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" title="Inactive" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'active','id'=>$row->id),'',true);?>"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
							?>
						<!--<input type="checkbox" <?php if($row->status==1){echo "CHECKED";}?> disabled="disabled">-->
						
					   </td>
					   <td>
							<!--<a class="action-icon" title="Edit" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'edit','id'=>$row->id),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>-->
							
							<a class="action-icon" title="View" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'view','id'=>$row->id,'parentid'=>$this->ParentPublicationInfo['id']),'',true);?>"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							
							<!--<a class="action-icon" title="Delete" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'delete','id'=>$row->id),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="9">&nbsp;</td></tr>';
						echo '<tr><td colspan="9"><div class="pagination">'.$this->paginationControl($this->issueList,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="9" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>

<script type="text/javascript">
function validate_search(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>