<?php
$formData=(isset($this->formData))?$this->formData:array();
?>
<script language="javascript" type="text/javascript">
function checkAllCheckboxes(frm)
{ 

 var ctr=0;
 var checked = "";
 if(checked == false){checked = true}else{checked = false}
 for (var ctr= 0; ctr < frm.length; ctr++)
 {
  field_name = frm.elements[ctr].name;
  if (field_name.indexOf("chk") != -1)
  {
   if (frm.elements[ctr].checked == false)
    {
    frm.elements[ctr].checked = true;
    //document.getElementById("check").style.display='none';
    //document.getElementById("uncheck").style.display='block';
    
    }else{
    frm.elements[ctr].checked = true;
    //document.getElementById("uncheck").style.display='none';
    //document.getElementById("check").style.display='block';
    }
  }
 }

}

function uncheckAllCheckboxes(frm)
{ 
 
 for (ctr=0; ctr < frm.length; ctr++)
 {
  field_name = frm.elements[ctr].name;
  if (field_name.indexOf("chk") != -1)
  {
   //if (frm.elements[ctr].checked)
   //{
    frm.elements[ctr].checked = false;
   //}
  }
 }
 //document.getElementById("uncheck").style.display='none';
 //document.getElementById("check").style.display='block';
}
 
function chk_checkbox()
{
var chks = document.getElementsByName('chk[]');
	var hasChecked = false;
	
	var myArray = new Array();
	 
	for (var i = 0; i < chks.length; i++)
	{
		if (chks[i].checked)
		{
		 	hasChecked = true;
			myArray = chks[i].value;
			
		}
	 
	}
	if (!hasChecked)
	{
		alert("Please select atleast one checkbox for performing action.");
		//chks[0].focus();
		return false;
	}
	 
}




function checked_text()
{
	if(document.frm.checkall.checked==true)
	{
		checkAllCheckboxes(document.frm);
	}
	if(document.frm.checkall.checked==false)
	{
		uncheckAllCheckboxes(document.frm);
	}
	
}
</script>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Subscription Management</h3></div>
	<div class="content-box-content">
	
		<div>
			<?php
				
			?>
			<br style="clear: both;"/>
			<div class="action-header">
				<span class="action-title">Subscription List for <?php echo $this->publicationname;?></span>
			 <ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'index'),'',true);?>">Back</a></li>
				</ul> 
			</div>
			<br style="clear: both;"/>	
			 
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			<br style="clear: both;"/>	
			
			<form name="frm" id="frm" action="" enctype="multipart/form-data" method="post">
		 
			<table class="table-list" cellpadding="0" cellspacing="0">
			   <tr>
				   <th>SL.No</th>
				   <th>Country</th>
				   <th>Language</th>
				   <th>Subscription Type</th>
				   <th>Number of Issues</th>
				   <th>Individual Price</th>
				   <th>Group Price</th>
				   <th>Status</th>
			   </tr>
			<?php 
			  $modelCountry    = new Publisher_Model_DbTable_Books();
			  $modelLanguage    = new Publisher_Model_DbTable_Books();
			  $modelPublications=new Admin_Model_DbTable_Publications();	
			  if(isset($this->subscriptiondata) && count($this->subscriptiondata)>0)
			  {
				$sNumber=1;
				foreach($this->subscriptiondata as $row)
				{
					$countryRecord   = $modelCountry->getCountryName($row->country_sub);
					$languageRecord   = $modelLanguage->getLanguageName($row->language_sub);
					
					
			
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td>
					   <?php
							echo $countryRecord['country'];
						?></td>						
					   <td>
					  <?php
							echo $languageRecord['language_name'];
						?></td>	   
					   <td><?php echo $row->subscription_type; ?></td>
					   <td><?php echo $row->number_of_issues; ?></td>
					   <td><?php echo $row->individual_price; ?></td>
					   <td><?php echo $row->group_price_sub; ?></td>
					   <td>
					   <?php 
							if($row->admin_approve=='1')
							{
							?>
							<a class="action-icon" title="Active" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'inactivesubscription','id'=>$row->id,'pub_id'=>$row->product_id),'',true);?>"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" title="Inactive" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'activesubscription','id'=>$row->id,'pub_id'=>$row->product_id),'',true);?>"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
						 ?>
							</td>
					   
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="9">&nbsp;</td></tr>';
						echo '<tr><td colspan="9"><div class="pagination">'.$this->paginationControl($this->prodList,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="9" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
			</form>
		</div>

	</div>
</div>

<script type="text/javascript">
function validate_search(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>