<ul>
	<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/index/transactionhistory/">Transaction History</a></li>
	<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/index/profilesettings/">Profile settings</a></li>
	<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/index/changepwd/">Change Password</a></li>
	<!-- <li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/index/purchasepoints/">Purchase Points</a></li> -->
	<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/index/grouppublication/">Group Publication</a></li>
	<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/index/devicetracking/">Device Tracking</a></li>
</ul>