<?php
$queryString = ($_SERVER['QUERY_STRING'] != '') ? '?' . $_SERVER['QUERY_STRING'] : '';
global $tab;
global $tab_ajax;
?>
<div class="pagination" style="width:100%">
    <div style="float:left;width:28%">
    </div>
    <div style="float:right;width:70%;">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->first)).$queryString; ?>" onclick="return pagination(this.href,'<?php echo $tab;?>','<?php echo $tab_ajax;?>');">Start</a> |
        <?php else: ?>
                <span class="disabled">Start</span> |
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)).$queryString; ?>" onclick="return pagination(this.href,'<?php echo $tab;?>','<?php echo $tab_ajax;?>');">&lt; Previous</a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)).$queryString; ?>" onclick="return pagination(this.href,'<?php echo $tab;?>','<?php echo $tab_ajax;?>');"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->next)).$queryString; ?>" onclick="return pagination(this.href,'<?php echo $tab;?>','<?php echo $tab_ajax;?>');">Next &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Next &gt;</span> |
        <?php endif; ?>
		
		
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
           <a href="<?= $this->url(array('page' => $this->last)).$queryString; ?>" onclick="return pagination(this.href,'<?php echo $tab;?>','<?php echo $tab_ajax;?>');">End</a>
        <?php else: ?>
            <span class="disabled">End</span>
        <?php endif; ?>
		
        &nbsp; Page <?= $this->current; ?> of <?= $this->last; ?>
    </div>
 </div>
 

<script type="text/javascript">

	function pagination(ajax_url,result_tab,tab_ajax)
	{
		$.ajax({
			type: "POST",
			url: ajax_url,
			async: false,
			data: "tab_ajax="+tab_ajax,
			success: function(result) {				
				$('#tab'+result_tab).html(result);
				//$('#tab'+result_tab).hide().html(result).fadeIn("slow");
			}
		});
		
		return false;
	}

</script>
