<!--left sidebar -->
<aside class="right_panel search_left"> 
<h5>Category</h5>
<?php
$catsearchUrl=$this->serverUrl().$this->baseUrl().'/search/index/publication/';
if(isset($this->categoriesList) && count($this->categoriesList)>0)
{
?>
<ul>
<?php
	foreach($this->categoriesList as $key=>$catArray)
	{
		?>
		<li><a href="<?php echo $catsearchUrl.strtolower(trim($catArray['category_name']));?>"><?php echo $catArray['category_name'].'('.$catArray['total_publications'].')';?></a></li>
		<?php
	}
?>
<li><a href="<?php echo $this->serverUrl().$this->baseUrl().'/search/';?>">view all</a></li>
</ul>
<?php
}
?>

<h5>Genre</h5>
<?php
$genresearchUrl=$this->serverUrl().$this->baseUrl().'/search/index/publication/genre/id/';
if(isset($this->genresList) && count($this->genresList)>0)
{
?>
<ul>
<?php
	foreach($this->genresList as $key=>$genreArray)
	{
		?>
		<li><a href="<?php echo $genresearchUrl.$genreArray['id'];?>"><?php echo $genreArray['genre'].'('.$genreArray['total_publications'].')';?></a></li>
		<?php
	}
?>
<li><a href="<?php echo $this->serverUrl().$this->baseUrl().'/search/';?>">view all</a></li>
</ul>
<?php
}
?>

<h5>Country</h5>
<?php
$storesearchUrl=$this->serverUrl().$this->baseUrl().'/search/index/publication/store/id/';
if(isset($this->allStoredWithPublications) && count($this->allStoredWithPublications)>0)
{
?>
<ul>
<?php
	foreach($this->allStoredWithPublications as $country_id=>$country_array)
	{
	?>
	<li><a href="<?php echo $storesearchUrl.$country_array['cid'];?>"><?php echo $country_array['cname'].'('.$country_array['total_publications'].')';?></a></li>
	<?php
	}
?>
<li><a href="<?php echo $this->serverUrl().$this->baseUrl().'/search/';?>">view all</a></li>
</ul>
<?php	
}
?>


<!--<h5>Days</h5>
<ul>
<li><a href="#">10 days</a></li>
<li><a href="#">30 days</a></li>
<li><a href="#">60 days</a></li>
<li><a href="#">90 days</a></li>
<li><a href="#">120 days</a></li>
<li><a href="#">True Crime</a></li>

</ul>-->
</aside>
<!--left sidebar -->

<!--right sidebar -->
<aside class="left_panel search_right">
		<ul class="tab">
			<li id="link_grid" class="grid active"><a href="javascript:void(0);">&nbsp;</a></li>
			<li id="link_view" class="list_view"><a href="javascript:void(0);">&nbsp;</a></li>
		</ul>
		<!-- //Tab buttons -->
<!-- //Tab 1 -->
<div id="conetnt2_grid" class="tabContents">

<?php
/*if(isset($this->searchKeyword) && !empty($this->searchKeyword))
{
?>
<h1>Result for "<?php echo $this->searchKeyword;?>"</h1>
<?php
}
else
{
?>
<h1>All Publications</h1>
<?php
}
*/
?>
	<aside class="right_listing"> 
	<div class="listing">
	<?php
	if(isset($this->approvedPublicatiobList) && !empty($this->approvedPublicatiobList) && count($this->approvedPublicatiobList)>0)
	{
	/*echo"<pre>";
	print_r($this->approvedPublicatiobList);
	echo"</pre>";
	*/
	?>
		<ul>
		<?php
		$modelAuthor = new Publisher_Model_DbTable_Publishers();
		$modelLanguage = new Admin_Model_DbTable_Languages();
		$modelImage = new Publisher_Model_DbTable_BookImages();
		
		foreach($this->approvedPublicatiobList as $publicationArray)
		{
		$authorInfo = $modelAuthor->getInfoByPublisherId($publicationArray['author_id']);
		$langDetail=$modelLanguage->fetchRow('id="'.$publicationArray['language_id'].'"');
		$imageInfo = $modelImage->getImageInfoByProductId($publicationArray['product_id']);
		?>
			<li>
				<div class="produt_img">
				<?php
				if(is_file(USER_UPLOAD_DIR.'thumb1_'.$imageInfo['image_name']))
				{
				?>
				<img  src="<?php echo $this->serverUrl().$this->baseUrl()."/".USER_UPLOAD_DIR.'thumb1_'.$imageInfo['image_name'];?>" alt="<?php echo$publicationArray['title'];?>">
				<?php
				}
				else
				{
				?>
				<img src="<?php echo $this->serverUrl().$this->baseUrl()."/public/css/default/images/noimage.jpg";?>" alt="<?php echo$publicationArray['title'];?>">
				<?php
				}
				?>
				</div>
				<div class="date"><?php $date = new Zend_Date(strtotime($publicationArray['publish_time']));print $date;//print $date->toString('YYYY-MM-dd HH:mm:ss');
				?></div>
				<div class="price">$<?php echo $publicationArray['price'].'('.$publicationArray['language_id'].')';?></div>
			</li>
		<?php
		}
		?>
		</ul>
		<?php
		if($this->totalCount>$this->pageSize)
		{
			global $tab,$tab_ajax;
			$tab=2; $tab_ajax='book';
			echo $this->paginationControl($this->approvedPublicatiobList,'Sliding','pagination.phtml');
		}
	}
	else
	{	
	?>
	<h1>Publication Not Found!</h1>
	<?php
	}	
	?>
	</div>
	
	
</aside>
</div>
 
 <!-- //Tab 2 -->
<div id="conetnt2_view" class="tabContents" style="display:none;">
	<h1>Result for "Keyword"L</h1>
	<aside class="right_listing"> 
	<div class="listing">
		<div class="slides marg">
		<div class="book"><img src="images/image1.jpg" alt=""></div>
			<div class="info">
				<a href="#">The Lorem Ipsum</a><br>
				<span>Adipisicing elit</span>
				<p class="price">$  9.99 </p>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>
			</div>
		</div>
		
		<div class="slides marg">
		<div class="book"><img src="images/image4.jpg" alt=""></div>
			<div class="info">
				<a href="#">The Lorem Ipsum</a><br>
				<span>Adipisicing elit</span>
				<p class="price">$  9.99 </p>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>
			</div>
		</div>
		
		<div class="slides marg">
		<div class="book"><img src="images/image1.jpg" alt=""></div>
			<div class="info">
				<a href="#">The Lorem Ipsum</a><br>
				<span>Adipisicing elit</span>
				<p class="price">$  9.99 </p>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>
			</div>
		</div>
		
		<div class="slides marg">
		<div class="book"><img src="images/image2.jpg" alt=""></div>
			<div class="info">
				<a href="#">The Lorem Ipsum</a><br>
				<span>Adipisicing elit</span>
				<p class="price">$  9.99 </p>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>
			</div>
		</div>
		
		<div class="slides marg">
		<div class="book"><img src="images/image3.jpg" alt=""></div>
			<div class="info">
				<a href="#">The Lorem Ipsum</a><br>
				<span>Adipisicing elit</span>
				<p class="price">$  9.99 </p>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>
			</div>
		</div>
		
	</div>
</aside>
		<div style="float: right; width: 62%;"><h2>Pagination</h2></div>
</div>
</aside>
<!--right sidebar -->
