<?php
$cancelUrl=$this->url(array('module'=>'company','controller'=>'profile','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'company','controller'=>'','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-4');";
}
else
{
	$return_function="getSettingPanel();";
}

?>
<div id="panel">
	<div class="panel-header"><h3>My Profile</h3></div>
	<div class="panel-content">
		<div class="panel-sub-content">
			
			<div class="action-header">
			<span class="action-title">&nbsp;</span>
			<ul class="horizonal-menu">
				<li class="back"><a href="<?php echo $backUrl;?>" title="Back" onclick="return <?php echo $return_function;?>">Back</a></li>
			</ul>
			</div>
						
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		<br  clear="all"/>
			
			<table cellpadding="10" cellspacing="10" style="width:350px; margin:0 auto; border-spacing:10px;">
				<tr>
					<td width="30%" style="font-family:Verdana, Arial, Helvetica, sans-serif; font-weight:bold; font-size:12px;">First Name</td>
					<td><?php echo $this->profileInfo['first_name'];?></td>
				</tr>
				<tr>
					<td width="30%" style="font-family:Verdana, Arial, Helvetica, sans-serif; font-weight:bold; font-size:12px;">Last Name</td>
					<td><?php echo $this->profileInfo['last_name'];?></td>
				</tr>
				<tr>
					<td width="30%" style="font-family:Verdana, Arial, Helvetica, sans-serif; font-weight:bold; font-size:12px;">Username</td>
					<td><?php echo $this->profileInfo['user_email'];?></td>
				</tr>
				
									
				<tr>
					<td width="30%" style="font-family:Verdana, Arial, Helvetica, sans-serif; font-weight:bold; font-size:12px;">Country</td>
					<td>
					<?php
					$modelcompany = new Company_Model_DbTable_Companies();
					$countryInfo=$modelcompany->getCountryInfo($this->profileInfo['country']);
					?>
					<?php echo $countryInfo['country'];?>
					</td>
				</tr>
				
				<tr>
					<td width="30%" style="font-family:Verdana, Arial, Helvetica, sans-serif; font-weight:bold; font-size:12px;">Phone</td>
					<td><?php echo $this->profileInfo['phone'];?></td>
				</tr>
				
				<tr>
					<td width="30%" class="tdrightBold">&nbsp;</td>
					<td>
					<a href="<?php echo $this->url(array('module'=>'company','controller'=>'profile','action'=>'updateprofile'),'',true);?>" title="Edit Profile" onclick="return goToPage(this.href,'tab4','dashboard');" ><input type="button" value="Edit Profile" name="btnEdit" class="button-Save" /></a>
					<input type="button" value="Cancel" name="btnCancel" title="Cancel" class="button-cancel" onclick="return <?php echo $return_function;?>" /></td>
				</tr>
			</table>
		</div>	
	</div>
</div>