<?php 
$currUrl=$this->url();
$cancelUrl=$this->url(array('module'=>'company','controller'=>'index','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'company','controller'=>'index','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();


if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-4');";
}
else
{
	$return_function="getSettingPanel();";
}

?>
<div id="panel">
	<div class="panel-header"><h3>Edit Profile</h3></div>
	<div class="panel-content">
		<div class="panel-sub-content">
		
		<div class="action-header">
			<span class="action-title">&nbsp;</span>
			<ul class="horizonal-menu">
				<li class="back"><a href="<?php echo $backUrl;?>" title="Back" onclick="return <?php echo $return_function;?>">Back</a></li>
			</ul>
		</div>
				
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
	
		<form id="form-add-user" method="post" onsubmit="return validate_common_form('form-add-user','<?php echo $currUrl;?>','tab4');">
			<table>
			<!--<tr>
				<td class="tdleftBold">User Type<span class="required">*</span> : </td>
				<td>
			    <select name="user_type" id="user_type" class="req" message="Please select a type">
			    <option value="">Select</option>
			    <option value="author" <?php if($formData["user_type"]=="author"){ ?> selected <?php } ?>>Author</option>
				<option value="company"  <?php if($formData["user_type"]=="company"){ ?> selected <?php } ?>>company</option>
				</select>
				<?php if(array_key_exists('user_type',$formErrors)){echo '<div class="inline-error">'.$formErrors['user_type'].'</div>';}?>
				</td>
			</tr>-->
				<tr>
									<td class="tdleftBold">Company Name<span class="required">*</span> : </td>
									<td>
										<input type="text" name="name" id="name" value="<?php if(isset($formData['name'])){echo $formData['name'];}?>"  class="req form-textfield"  message="Please enter company name."/>
										<?php if(array_key_exists('name',$formErrors)){echo '<div class="inline-error">'.$formErrors['name'].'</div>';}?>
									</td>
								</tr>
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">First name<span class="required">*</span> : </td>
				<td>
				<input type="text" name="first_name" id="first_name" value="<?php if(isset($formData['first_name'])){echo $formData['first_name'];}?>"  class="req form-textfield"  message="Please enter first name"/>
				<?php if(array_key_exists('first_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['first_name'].'</div>';}?>
				</td>
			</tr>
			
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>				
			
			<tr>
				<td class="tdleftBold">Last Name<span class="required">*</span> : </td>
				<td>
					<input type="text" name="last_name" id="last_name" value="<?php if(isset($formData['last_name'])){echo $formData['last_name'];}?>"  class="req form-textfield"  message="Please enter last name" />
					<?php if(array_key_exists('last_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['last_name'].'</div>';}?>
				</td>
			</tr>
			
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">Country<span class="required">*</span> : </td>
				<td>
				
					<?php
					$modelcompany = new Company_Model_DbTable_Companies();
					$countryList=$modelcompany->getCountryList();
					?>
					
					<select name="country" id="country">
					<option value="">Select Country</option>
					
					<?php
					for($ii=0;$ii<count($countryList);$ii++)
					{
					?>
					<option value="<?php echo $countryList[$ii]['id']; ?>" <?php if($formData["country"]==$countryList[$ii]["id"]){ ?> selected <?php } ?> ><?php echo $countryList[$ii]['country']; ?></option>
					<?php
					}
					?>		   
					</select>
					
					<?php if(array_key_exists('country',$formErrors)){echo '<div class="inline-error">'.$formErrors['country'].'</div>';}?>

				</td>
			</tr>
			
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
								
			<!--<tr>
				<td class="tdleftBold">Pincode<span class="required">*</span> : </td>
				<td>
					<input type="text" name="pincode" id="pincode" value="<?php if(isset($formData['pincode'])){echo $formData['pincode'];}?>"  class="req form-textfield"  message="Please enter pincode" />
					<?php if(array_key_exists('pincode',$formErrors)){echo '<div class="inline-error">'.$formErrors['pincode'].'</div>';}?>
				</td>
			</tr>-->
			
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
								
			<tr>
				<td class="tdleftBold">Phone : </td>
				<td>
					<input type="text" name="phone" id="phone" value="<?php if(isset($formData['phone'])){echo $formData['phone'];}?>"  class="form-textfield"  message="Please enter phone" />
					<?php if(array_key_exists('phone',$formErrors)){echo '<div class="inline-error">'.$formErrors['phone'].'</div>';}?>
				</td>
			</tr>
			
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">&nbsp;</td>
				<td>
					<input type="hidden" name="update_profile" value="Update Profile">
					<input type="submit" value="Update" title="Update Profile" class="button-Save" />
					<input type="button" value="Cancel" name="btnCancel" title="Cancel" class="button-cancel" onclick="return <?php echo $return_function;?>" />
				</td>
			</tr>
			
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
		</table>
	</form>
	</div>
</div>	
</div>

