<?php
$backUrl=$this->url(array('module'=>'company','controller'=>'index','action'=>'index'),'',true);

if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-2');";
}
elseif(isset($formData['tab_ajax']) && $formData['tab_ajax']=='mysetting')
{
$return_function="getSettingPanel('hide-2');";
}
else
{
	$return_function="goToPage('".$backUrl."','tab2','subscription');";
}
?>
<div id="panel">
	<div class="panel-header"><h3>Subscription List</h3>
	<?php
	if($this->sessCompanyInfo->parent_id==0)
	{
	?>
	<a href="<?php echo $this->url(array('module'=>'company','controller'=>'subscription','action'=>'manage'),'',true);?>" title="Manage Subscription" onclick="return goToPage(this.href,'tab2','Subscription');" class="addbook">Manage Subscription</a>
	<?php
	}
	?>
	</div>
	<div class="panel-content">
		<div class="panel-sub-content">
			
			<!--<div class="action-header">
				<span class="action-title">&nbsp;</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>-->	
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
		
		<?php
		if(empty($this->sessCompanyInfo->parent_id))
		{
		?>
		<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="30%" align="center">Item</th>
				   <th width="10%" align="center">Total Downloads</th>
				   <th width="20%" align="center">Last Download On</th>
				   <th width="10%" align="center">Status</th>
				   <th width="10%" align="center">Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->MySubscriptionsList) && count($this->MySubscriptionsList)>0)
			  {
				$sNumber=1;
				foreach($this->MySubscriptionsList as $row)
				{
			?>
					<tr>
					<td valign="top"><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td>
					<?php
					$itemDetail = $this->modelCompanySubscription->getProductInfo($row['product_id']);
					//print_r($itemDetail);
					if(!empty($itemDetail['parent_brand_id']))
					{
						$parentItemDetail = $this->modelCompanySubscription->getProductInfo($itemDetail['parent_brand_id']);
						$modelCategory = new Publisher_Model_DbTable_Books();
						//$categoryDetails=$modelCategory->getCategoryInfo($parentItemDetail['cat_id']);
						$getBrandInfo=$modelCategory->getBrandInfo($parentItemDetail['title']);
					}
					else
					{
						$getBrandInfo="";
					}
					
					//print_r($getBrandInfo);
					
					$imageDetail=$this->modelCompanySubscription->getImageInfo($row['product_id']);
					
					if(isset($getBrandInfo) && !empty($getBrandInfo))
					{
					//echo "<a href=".$this->url(array('module'=>'company','controller'=>'subscription','action'=>'downloadpubfile','id'=>$row['product_id'],'tab_ajax'=>'subscription'),'',true)." title='Click To Download'>";
					
					if(file_exists(USER_UPLOAD_DIR.$imageDetail['image_name_thumb']))
					{
					?>
					<img src="<?php echo $this->serverUrl().$this->baseUrl()."/".USER_UPLOAD_DIR.$imageDetail['image_name_thumb'];?>" height="100" width="100"><br />
					<?php
					}
					?>
					<?php 
					echo $getBrandInfo['brand'].'('.$itemDetail['title'].')';
					echo"</a>";
					?>
					<?php
					}
					else
					{
					//echo "<a href=".$this->url(array('module'=>'company','controller'=>'subscription','action'=>'downloadpubfile','id'=>$row['product_id'],'tab_ajax'=>'subscription'),'',true)." title='Click To Download'>";
					if(file_exists(USER_UPLOAD_DIR.$imageDetail['image_name_thumb']))
					{
					?>
					<img src="<?php echo $this->serverUrl().$this->baseUrl()."/".USER_UPLOAD_DIR.$imageDetail['image_name_thumb'];?>" height="100" width="100"><br />
					<?php
					}
					echo $itemDetail['title'];
					//echo"</a>";
					?>
					<?php
					}
					?>
					</td> 
					<td valign="top"><?php echo $row['total_downloads'];?></td>
					   <td valign="top"><?php echo $row['updated_date'];?></td>
					   <td valign="top">
						<?php 
						if($row['status']=='1')
						{
						?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'subscription','action'=>'inactive','id'=>$row['id']),'',true);?>" title="Click To Deactivate User" onclick="return inactive(this.href,'tab2','subscription');"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/publisher/images/active.png"/></a>
						<?php
						}
						else
						{
						?>
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'subscription','action'=>'active','id'=>$row['id']),'',true);?>" title="Click To Activate User" onclick="return active(this.href,'tab2','subscription');"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/publisher/images/inactive.png"/></a>
						<?php
						}
						?>
						
					   </td>
					   <td valign="middle">
					   
						<!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'subscription','action'=>'edit','id'=>$row['id']),'',true);?>" title="Edit User" onclick="return goToPage(this.href,'tab2','subscription');"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/publisher/images/icon_edit.png"/></a>-->
						
						<!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'subscription','action'=>'view','id'=>$row['id']),'',true);?>" title="View User" onclick="return goToPage(this.href,'tab2','subscription');"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/publisher/images/application_view_detail.png"/></a>-->
							
						<?php
						$modelGroupSubscription = new Company_Model_DbTable_GroupSubscriptions();
						$publicationSubscriptionList=$modelGroupSubscription->isExist("publication_id=".$row['product_id']." AND company_id=".$this->sessCompanyInfo->id);
						if($publicationSubscriptionList)
						{
						?>
						<a class="action-icon" href="javascript:void(0);" title="Delete" onclick="javascript:alert('Delete all it\'s subscriptions first!'); return false;"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/publisher/images/trash.gif"/></a>
						<?php
						}
						else
						{
						?>
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'subscription','action'=>'delete','id'=>$row['id']),'',true);?>" title="Delete" onclick="return deleteAction(this.href,'tab2','subscription');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/publisher/images/trash.gif"/></a>
						<?php
						}
						?>
						</td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab; $tab=2;
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->MySubscriptionsList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
			<?php
			}
			else
			{
			?>
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="30%" align="center">Publication</th>
				   <th width="30%" align="center">Assigned On</th>
				</tr>
			 <?php 
			  if(isset($this->MySubscriptionsList) && count($this->MySubscriptionsList)>0)
			  {
				$sNumber=1;
				foreach($this->MySubscriptionsList as $row)
				{
			?>
					<tr>
					<td valign="top"><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td>
					<?php
					$itemDetail = $this->modelCompanySubscription->getProductInfo($row['publication_id']);
					//print_r($itemDetail);
					if(!empty($itemDetail['parent_brand_id']))
					{
						$parentItemDetail = $this->modelCompanySubscription->getProductInfo($itemDetail['parent_brand_id']);
						$modelCategory = new Publisher_Model_DbTable_Books();
						//$categoryDetails=$modelCategory->getCategoryInfo($parentItemDetail['cat_id']);
						$getBrandInfo=$modelCategory->getBrandInfo($parentItemDetail['title']);
					}
					else
					{
						$getBrandInfo="";
					}
					
					//print_r($getBrandInfo);
					
					$imageDetail=$this->modelCompanySubscription->getImageInfo($row['publication_id']);
					
					if(isset($getBrandInfo) && !empty($getBrandInfo))
					{
					//echo "<a href=".$this->url(array('module'=>'company','controller'=>'subscription','action'=>'downloadpubfile','id'=>$row['publication_id'],'tab_ajax'=>'subscription'),'',true)." title='Click To Download'>";
					
					if(file_exists(USER_UPLOAD_DIR.$imageDetail['image_name_thumb']))
					{
					?>
					<img src="<?php echo $this->serverUrl().$this->baseUrl()."/".USER_UPLOAD_DIR.$imageDetail['image_name_thumb'];?>" height="100" width="100"><br />
					<?php
					}
					?>
					<?php 
					echo $getBrandInfo['brand'].'('.$itemDetail['title'].')';
					echo"</a>";
					?>
					<?php
					}
					else
					{
					//echo "<a href=".$this->url(array('module'=>'company','controller'=>'subscription','action'=>'downloadpubfile','id'=>$row['product_id'],'tab_ajax'=>'subscription'),'',true)." title='Click To Download'>";
					if(file_exists(USER_UPLOAD_DIR.$imageDetail['image_name_thumb']))
					{
					?>
					<img src="<?php echo $this->serverUrl().$this->baseUrl()."/".USER_UPLOAD_DIR.$imageDetail['image_name_thumb'];?>" height="100" width="100"><br />
					<?php
					}
					echo $itemDetail['title'];
					//echo"</a>";
					?>
					<?php
					}
					?>
					</td> 
					<td valign="top"><?php echo $row['assigned_date'];?></td>
					</tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax; 
					$tab=2;$tab_ajax='subscription';
					
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->MySubscriptionsList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
			<?php
			}
			?>			
		</div>	
	</div>
</div>

