<div id="panel">
	<div class="panel-header">Job Seekers Management</div>
	<div class="panel-content">
		
		<div class="panel-sub-content">

			<br style="clear: both;"/>
			<div class="action-header">
				<span class="action-title">Job Seekers List</span>
			</div>
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			<br style="clear: both;"/>	
			<table class="table-list" cellpadding="0" cellspacing="0">
			   <tr>
				   <th>SL.No</th><th>ID</th><th>Name</th><th>Email Id</th><th>Date Registered</th><th>Current Employer</th><th># Years Experience</th><th style="width:80px;">Action</th>
			   </tr>
			<?php 
			  if(isset($this->userList) && count($this->userList)>0)
			  {
				$sNumber=1;
				foreach($this->userList as $row)
				{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $row->id;?></td> 
					   <td>&nbsp;</td>
					   <td>&nbsp;</td> 
					   <td><?php echo CommonFunctions::formatDate($row->added_date);?></td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'candidates','action'=>'edit','id'=>$row->id),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'candidates','action'=>'delete','id'=>$row->id),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_delete.png"/></a>
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="8">&nbsp;</td></tr>';
						echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->userList,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>