<?php
$productHistory = $this->tempOrderData;
?>
<section id="middle">

<!--cart section start -->
<div class="cart error_page" id="cardId">
<p>404

Sorry, this page isn't available
The link you followed may be broken, or the page may have been removed.

Please go to <a href="<?php echo $this->serverUrl().$this->baseUrl();?>" >Home</a></p>
<img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/pagenotfound.jpg" />

</div>
<div id="det_tot"></div>
</form>
<!--cart section start end -->
</section>
 


