<script type="text/javascript">	
	$(document).ready(function(){			
		new JsDatePick({
			useMode:2,
			target:"from_date",
			dateFormat:"%Y-%m-%d"
			/*selectedDate:{				This is an example of what the full configuration offers.
				day:5,						For full documentation about these settings please see the full version of the code.
				month:9,
				year:2006
			},
			yearsRange:[1978,2020],
			limitToToday:false,
			cellColorScheme:"beige",
			dateFormat:"%m-%d-%Y",
			imgPath:"img/",
			weekStartDay:1*/
		});
	});
	
	$(document).ready(function(){			
		new JsDatePick({
			useMode:2,
			target:"to_date",
			dateFormat:"%Y-%m-%d"
			/*selectedDate:{				This is an example of what the full configuration offers.
				day:5,						For full documentation about these settings please see the full version of the code.
				month:9,
				year:2006
			},
			yearsRange:[1978,2020],
			limitToToday:false,
			cellColorScheme:"beige",
			dateFormat:"%m-%d-%Y",
			imgPath:"img/",
			weekStartDay:1*/
		});
	});
	
</script>
<?php
$currUrl=$this->url();
$addUrl=$this->url(array('module'=>'publisher','controller'=>'book','action'=>'create'),'',true);
$bookList=(isset($this->bookList))?$this->bookList:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
$formData=(isset($this->formData))?$this->formData:array();
$searchAllUrl=$this->url(array('module'=>'publisher','controller'=>'book','action'=>'index'),'',true);
?>
<div id="panel">
	<div class="panel-header">
	    <h3>My Reports</h3>
	    <a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'book','action'=>'create'),'',true);?>" onclick="return goToPage(this.href,'tab2','book');" title="Add New Publication" class="addbook"></a>
	</div>
	
	<div class="panel-content" id="addbook">
		<div class="panel-sub-content" >
		
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
			<form name="form-search" id="form-search" method="post" onsubmit="return validate_common_form('form-search','<?php echo $currUrl;?>','tab9');">
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Publications</th>
				</tr>
				
				 <tr>
					<td width="100%" colspan="8">Select Manager:<select name="manager" id="manager" onchange="getuserlist('<?php echo $this->parentPublisherId;?>',this.value,'');"><option value="" >Select One</option><option value="publication_manager" <?php if($formData['manager']=='publication_manager') {?>selected<?php } ?> >Publication Manager</option><option value="account_manager" <?php if($formData['manager']=='account_manager') {?>selected<?php } ?>  >Account Manager</option></select> 
						Manager List:
					<select name="userList" id="userlist" ></select>
					<?php
					if($formData['manager']!='' && $formData['userList']!='')
					{
					?>
						<script type="text/javascript">getuserlist('<?php echo $this->parentPublisherId;?>','<?php echo $formData['manager'];?>','<?php echo $formData['userList'];?>');</script>
					<?php
					}
					?></br>
					From Date <input type="text" size="12" name="from_date" id="from_date" value="<?php echo $formData['from_date'];?>" />
					To Date <input type="text" name="to_date" id="to_date" value="<?php echo $formData['to_date'];?>" />
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add">
					<input type="button" name="showall" value="Show All" class="button-Add" onclick="return goToPage('<?php echo $currUrl;?>','tab9','report');" />
					</td>
				</tr>
				</table>
			 </form>
			 <br  clear="all"/>
			 <br  clear="all"/>
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="15%" align="center">Title / Brand</th>
				   <th width="15%" align="center">Genre</th>
				   <th width="15%" align="center">Author / Publisher</th>
				   <th width="15%" align="center">Type</th>
				   <th width="25%" align="center">Assigned Member</th>
				   <th width="5%" align="center">No Of Download</th>
				   <th width="5%" align="center">No Of Purchased</th>
				   <th width="15%" align="center">Total Price</th>
			   </tr>			   
			<?php 
			/*echo "<pre>";
			print_r($this->bookList);
			*/
			$this->modelPublisher = new Publisher_Model_DbTable_Publishers();
			$this->modelBooks = new Publisher_Model_DbTable_Books();			
			  if(isset($this->bookList) && count($this->bookList)>0)
			  { 
				$sNumber=1;
				foreach($this->bookList as $row)
				{
			?>
					<tr>
					<td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td>
					<?php
					$modelCategory = new Publisher_Model_DbTable_Books();
					$categoryDetails=$modelCategory->getCategoryInfo($row['cat_id']);
					$getBrandInfo=$modelCategory->getBrandInfo($row['title']);					
					
						?>
							<?php echo stripslashes($row['title']);?>
						<?php
					
					?>
					</td> 
					<td>
					<?php					
					$modelGenre = new Publisher_Model_DbTable_Genres();
					$genreDetails=$modelGenre->getGenreInfo($row['product_type']);
					echo $genreDetails['genre'];
					?></td>
					<td>
					<?php
					/*if((strtolower(trim($categoryDetails['category_name']))==strtolower(trim('Newspaper')) || strtolower(trim($categoryDetails['category_name']))==strtolower(trim('Newspapers')) || strtolower(trim($categoryDetails['category_name']))==strtolower(trim('Magazine')) || strtolower(trim($categoryDetails['category_name']))==strtolower(trim('Magazines'))) && $row['title']>0)
					{*/
						echo $row['publisher'];
					//}
					/*else
					{
						$modelAuthor = new Publisher_Model_DbTable_Books();
						$authorDetails=$modelAuthor->getAuthorInfo($row['author_id']);
					    echo $authorDetails['first_name']." ".$authorDetails['last_name'];
					}*/	
					?>
					</td>
				    <td>
					<?php
					echo $categoryDetails['category_name'];
					?>
					</td> 
					<td>
					<?php
					/*
					if($row['group_user_id']!='')
					{
						$userData = $this->modelPublisher->getInfoByPublisherId($row['group_user_id']);
						echo $name = $userData['first_name']." ".$userData['last_name'];
					}
					else
					{
						$assignPublisherUser = $this->modelBooks->getPublicationAssignUser($row['id'],$row['publisher_id']);
						for($i=0;$i<count($assignPublisherUser);$i++)
						{
							$userData = $this->modelPublisher->getInfoByPublisherId($assignPublisherUser[$i]['group_user_id']);
							echo $name = $userData['first_name']." ".$userData['last_name']."</br>";
						}
					}*/
					//echo $row['group_user_id'];
					?>							
					</td>
				 	<td>
				 	<?php
				 	$credit_details = $this->modelBooks->getProductCreditHistory($row['id']);
					if($credit_details['total_count']!='')
					{
						echo $credit_details['total_count'];
					}
					else {
						echo "0";
					}
				 	?>
				 	</td>
				 	
				 	<td>
				 		<?php
				 		if($credit_details['total_count']!='')
						{
							echo $credit_details['total_count'];
						}
						else {
							echo "0";
						}
				 	?>
				 	</td>
				 	<td>
				 		<?php
				 		echo $credit_details['total_price']
				 		?>
				 	</td>
					 
				   </tr>
			<?php
					$sNumber++;
				}				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax;
					$tab=9; $tab_ajax='report';
					echo '<tr><td colspan="9">&nbsp;</td></tr>';
					echo '<tr><td colspan="9"><div class="pagination">'.$this->paginationControl($this->bookList,'Sliding','pagination.phtml').'</div></td></tr>';
				}				
			  }
			  else
			  {
				echo '<tr><td colspan="10" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>	
	</div>
</div>
<script type="text/javascript">
	function getuserlist(pId,val,userid)
	{
		//alert(val);
		$.post("<?php echo $this->serverUrl().$this->baseUrl();?>/publisher/report/getmanageruser/",{"type":val,"pId":pId,"user_id":userid},function(data){
			$("#userlist").html(data);
		});
	}
</script>
