<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'authors','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'authors','action'=>'index'),'',true);

$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>

<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Author Management</h3></div>
	<div class="content-box-content">
	
		<div>
			<div class="action-header">
				<span class="action-title">Author Details</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>
		
			<br  clear="all"/>
			
<table class="table-form" cellpadding="0" cellspacing="0">

<tr>
<td width="20%" class="tdrightBold">Username </td>
<td><?php echo $formData['username']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Email </td>
<td><?php echo $formData['emailid']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Name </td>
<td><?php echo $formData['first_name']." ".$formData['last_name']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Location: </td>
<td><?php echo $formData['location']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">City: </td>
<td><?php echo $formData['city']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">State: </td>
<td><?php echo $formData['state']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Country: </td>
<td><?php echo $formData['country']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Pincode </td>
<td><?php echo $formData['pincode']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Profile Image </td>
<td><?php echo $formData['profile_image']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Phone: </td>
<td><?php echo $formData['phone']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Join Date: </td>
<td><?php echo $formData['add_time']; ?></td>
</tr>

</table>
			
</div>

