<?php
$currUrl=$this->url();
$cancelUrl=$this->url(array('module'=>'publisher','controller'=>'','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'publisher','controller'=>'','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();


if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-4');";
}
else
{
	$return_function="getSettingPanel();";
}

?>
<div id="panel">
	<div class="panel-header"><h3>Change Password</h3></div>
	<div class="panel-content">
	
		<div class="panel-sub-content">
			
			<div class="action-header">
				<span class="action-title">&nbsp;</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back" onclick="return <?php echo $return_function;?>">Back</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br  clear="all"/>
			
			<form id="form-change-password" method="post" onsubmit="return validate_common_form('form-change-password','<?php echo $currUrl;?>','tab4');">
				
				<table cellpadding="0" cellspacing="0" class="change_password">
					<tr>
						<td width="45%" class="tdrightBold">Old Password<span class="required">*</span> : </td>
						<td>
							<input type="password" name="password" id="password" value="<?php if(isset($formData['password'])){echo $formData['password'];}?>" class="req form-textfield"  message="Please enter your current password"  invalidmessage="Please enter your current password"/>
							<?php if(array_key_exists('password',$formErrors)){echo '<div class="inline-error">'.$formErrors['password'].'</div>';}?>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td width="45%" class="tdrightBold">New Password<span class="required">*</span> : </td>
						<td>
							<input type="password" name="new_password" id="new_password" value="<?php if(isset($formData['new_password'])){echo $formData['new_password'];}?>" class="req form-textfield"  message="Please enter your new password"  invalidmessage="Please enter your new password"/>
							<?php if(array_key_exists('new_password',$formErrors)){echo '<div class="inline-error">'.$formErrors['new_password'].'</div>';}?>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td width="45%" class="tdrightBold">Confirm New Password<span class="required">*</span> : </td>
						<td>
							<input type="password" name="conf_new_password" id="conf_new_password" value="<?php if(isset($formData['conf_new_password'])){echo $formData['conf_new_password'];}?>" class="req form-textfield"  message="Please confirm your new password"  invalidmessage="Confirm password does not match"/>
							<?php if(array_key_exists('conf_new_password',$formErrors)){echo '<div class="inline-error">'.$formErrors['conf_new_password'].'</div>';}?>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td width="25%" class="tdrightBold">&nbsp;</td>
						<td>
							<input type="hidden" name="change_password" value="Update Password">
							<input type="submit" value="Save" title="Update Password" class="button-Save"/>
							<input type="button" value="Cancel" name="btnCancel" title="Cancel" class="button-cancel" onclick="return <?php echo $return_function;?>" />
						</td>
					</tr>
				  
				 </table>
			</form>
	</div>
</div>
