<?php
$producturrency = new Admin_Model_DbTable_Countries();
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
$this->modelPublisher = new Publisher_Model_DbTable_Publishers();
//echo "<pre>";
//print_r($this->trans_history_data);
$transDet = $this->trans_history_data;
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Transaction Management</h3></div>
	<div class="content-box-content">	
		<div>
			<br style="clear: both;"/>
			<div class="action-header">
				<span class="action-title">Order Has been <?php echo $transDet[0]['orderStatus'];?>. Please check your order details.<br/>
				Reference Id<br/>
				Order Id: <?php echo $transDet[0]['orderId'];?><br/>
				Transaction Id: <?php echo $transDet[0]['id'];?><br/>
				</span>
				
			</div>
			<br style="clear: both;"/>	
			<form id="form-search" method="post" onsubmit="return validate_search('form-search');">
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">View Orders</th>
				</tr>
				<tr>
					<td align="center" colspan="2">
					<div align="center">
						<table class="table-list" cellpadding="0" cellspacing="0">
							<tr>
								<th>Item</th>
								<th>Quantity</th>
								<th>Price</th>
								<th>Sub Total</th>
							</tr>
								
					<?php 
					if(count($this->order_list)>0)
					{
						foreach($this->order_list as $orderDetails)
						{
							$getCurrencyName = $producturrency->getCurrencyCode($orderDetails['store_id']);	
						?>
							<tr>
							<td><?php echo $orderDetails['book_name'];?></td>
							<td><?php echo $orderDetails['quantity'];?></td>
							<td>&#x20a6;<?php echo $producturrency->currencyconverter($getCurrencyName,"NGN",$orderDetails['price']);?></td>
							<td>&#x20a6;<?php echo $producturrency->currencyconverter($getCurrencyName,"NGN",$orderDetails['quantity']*$orderDetails['price']);?></td>
							</tr>
						<?php
							$total = $total+$orderDetails['quantity']*$orderDetails['price'];
						}
					}
					?>
					<tr><td colspan="4">Total: &#x20a6;<?php echo $producturrency->currencyconverter($getCurrencyName,"NGN",$total)?></td></tr>
					</table>
					<!-- <input type="button" name="showall" value="Export" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'reports','action'=>'exportordertxls',"orderid"=>$this->order_id),'',true);?>'" title="Export"/> -->
					</div>
					</td>
				</tr>
				</table>
			 </form>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			<br style="clear: both;"/>	
			<table class="table-list" cellpadding="0" cellspacing="0">
			 <?php 		
			  if(isset($this->trans_history_data) && count($this->trans_history_data)>0)
			  {
				$sNumber=1;
				foreach($this->trans_history_data as $row)
				{
			?>
					<tr>
					   <td>
					   Transaction Message:
					   </td>
					   <td>
					   <?php
					   echo $row['responseDescription'];
						?>
						</td>
				   </tr>
				   
				    <tr>
					   <td>
					   Masked PAN:
					   </td>
					   <td>
					   <?php
					   echo $row['pan'];
						?>
						</td>
				   </tr>
				   
				    <tr>
					   <td>
					   Card Holder Name:
					   </td>
					   <td>
					   <?php
					   echo $row['card_holder_name'];
						?>
						</td>
				   </tr>
				   
				     <tr>
					   <td>
					   Transaction Date Time:
					   </td>
					   <td>
					   <?php
					   echo $row['tranDateTime'];
						?>
						</td>
				   </tr>
				    <tr>
					   <td>
					   Merchant TranId:
					   </td>
					   <td>
					   <?php
					   echo $row['merchantTranId'];
						?>
						</td>
				   </tr>
				      <tr>
					   <td>
						Transaction Amount					   </td>
					   <td>
					   <?php
					   echo $row['purchaseAmount'];
						?>
						</td>
				   </tr>
				    <tr>
					   <td>
					  Transaction Currency:
					   </td>
					   <td>
					   <?php
					   echo $row['currency'];
						?>
						</td>
				   </tr>	
				  
				    <tr>
					   <td>
					   Authorization Code:
					   </td>
					   <td>
					   <?php
					  echo $row['approvalCodeScr'];
						?>
						</td>
				   </tr>
				    <tr>
					   <td>
					   Merchant Name:
					   </td>
					   <td>
						Evendor
						</td>
				   </tr>
				    <tr>
					   <td>
					   Site Url:
					   </td>
					   <td>
						http://miprojects2.com.php53-6.ord1-1.websitetestlink.com/projects/evendor
						</td>
				   </tr>
				 
				   
			<?php
					$sNumber++;
				}
			  }
			  else
			  {
				echo '<tr><td colspan="9" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>
		<div ><input type="button" name="print" id="print" value="Print" onClick="window.print()" /></div>
	</div>
</div>

<script type="text/javascript">
function validate_search(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}


function get_book_issues(ajax_url,parent_type_id,product_id)
{
//alert(ajax_url+'=>'+parent_type_id+'=>'+product_id);
	$.ajax({
	    type: "POST",
		url: ajax_url,
		async: false,
		data: "cat_id="+parent_type_id+"&product_id="+product_id,
		success: function(result) {
			//alert(result);
			$('#product_list').html(result);
		}
	});
	
	return false;
}

<?php
if(isset($formData["category"]) && !empty($formData["category"]))
{
?>
get_book_issues('<?php echo $title_brand_url;?>','<?php echo $formData["category"];?>','<?php echo $formData["product_id"];?>');
<?php
}
?>
</script>