<?php 
$cancelUrl=$this->url(array('module'=>'publisher','controller'=>'edition','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'publisher','controller'=>'edition','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

?>

<div id="panel">
	<div class="panel-header"><h3>View Edition</h3></div>
	<div class="panel-content">
		<div class="panel-sub-content">
		
		<div class="action-header">
			<span class="action-title">&nbsp;</span>
			<ul class="horizonal-menu">
				<li class="back"><a href="<?php echo $backUrl;?>" title="Back" onclick="return goToPage(this.href,'tab7','edition');">Back</a></li>
			</ul>
		</div>
		
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>

		<table>
			<tr>
				<td class="tdleftBold">Edition<span class="required">*</span> : </td>
				<td>
				<?php
				echo $formData['edition'];
				?>
				</td>
			</tr>
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">Added Date<span class="required">*</span> : </td>
				<td>
				<?php
				echo $formData['added_date'];
				?>
				</td>
			</tr>
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">Last Update<span class="required">*</span> : </td>
				<td>
				<?php
				echo $formData['updated_date'];
				?>
				</td>
			</tr>
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">Status<span class="required">*</span> : </td>
				<td>
				<?php
				if($formData['status']==1)
				{
					echo 'Active';
				}
				else
				{
					echo 'Inactive';
				}
				
				?>
				</td>
			</tr>
			<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">&nbsp;</td>
				<td>
				<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'edition','action'=>'edit','id'=>$formData['id']),'',true);?>" title="Edit edition" onclick="return goToPage(this.href,'tab7','edition');"><input type="button" value="Edit Edition" name="btnEdit" class="button-Save" /></a>
				<input type="button" value="Cancel" name="btnCancel" title="Cancel" class="button-cancel" onclick="return goToPage('<?php echo $cancelUrl;?>','tab7','edition');" />
				</td>
			</tr>
				
		</table>
	</div>
</div>	
</div>
