<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Points System</h3></div>
	<div class="content-box-content">
	
		<div>
		
			<div class="action-header">
				<span class="action-title">Add Points</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br  clear="all"/>
			
			<form id="form-add-faq" method="post" onsubmit="return validate_add_points('form-add-faq');">
			
				<table class="table-form" cellpadding="0" cellspacing="0">
					<tr>
						<td width="20%" class="tdrightBold">Points<span class="required">*</span> : </td>
						<td>
							<input type="text" name="points" id="points" value="<?php if(isset($formData['points'])){echo $formData['points'];}?>" class="req form-textfield"  message="Please enter points"  invalidmessage="Please enter valid points"/>
							<?php if(array_key_exists('points',$formErrors)){echo '<div class="inline-error">'.$formErrors['points'].'</div>';}?>
						</td>
					</tr>
					 
					<tr>
						<td width="20%" class="tdrightBold">Status : </td>
						<td>
							<input type="radio" name="status" value="1" checked="checked">Publish
							&nbsp;&nbsp;
							<input type="radio" name="status" value="0">Unpublish
						</td>
					</tr>
					<tr>
						<td width="20%" class="tdrightBold">&nbsp;</td>
						<td>
							<input type="submit" value="Add" class="button-Add" title="Add" />
							<input type="button" value="Cancel" name="btnCancel" class="button-cancel" onclick="window.location.href='<?php echo $cancelUrl;?>';" title="Cancel" />
						</td>
					</tr>
				  
				 </table>
			</form>
	</div>
</div>

<script type="text/javascript">
function validate_add_points(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>