<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Points System</h3></div>
	<div class="content-box-content">
	
		<div>

			<div class="action-header">
				<span class="action-title">Points System</span>
				<ul class="horizonal-menu">
					<li class="add"><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'add'),'',true);?>" title="Add Points">Add Points</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br style="clear: both;"/>	
			
			<table class="table-list" cellpadding="0" cellspacing="0">
			<tr>
				   <th width="5%">Sr.No</th>
				   <th width="5%">Point ID</th>
				   <th width="5%">Points</th>
				   <th width="10%">Added Date</th>
				   <th width="15%">Updated Date</th>
				   <th width="10%">Sort Order</th>
				   <th width="5%">Status</th>
				   <th width="10%">Action</th>
			</tr>
			
			<?php 
			  if(isset($this->pointsList) && count($this->pointsList)>0)
			  {
				$sNumber=1;
				$totalFaqs=$this->totalCount;
				foreach($this->pointsList as $row)
				{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $row->point_id;?></td> 
					   <td><?php echo $row->points;?></td>
					   <td><?php echo CommonFunctions::formatDate($row->add_date);?></td>
					   <td><?php echo CommonFunctions::formatDate($row->mod_date);?></td>
					   <td>
					   <select name="sort_order_<?php echo $row->point_id;?>" id="sort_order_<?php echo $row->point_id;?>" onchange="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'setsortorder','id'=>$row->point_id),'',true);?>/setorder/'+this.value" style="width:45px;">
					   
					   <!--<select name="sort_order_<?php echo $row->point_id;?>" id="sort_order_<?php echo $row->point_id;?>" onchange="return set_sort_order(this.id,this.value);">-->
					   <?php
					   for($i=1; $i<=$this->totalCount;$i++)
					   {
						?>
						<option <?php if($row->sort_order==$i)echo"selected";?>><?php echo $i;?></option>
						<?php
					   }
					   ?>
					   </select>
					   </td>
					   <td>
					   
					        <?php 
							if($row->status=='1')
							{
							?>
							<a class="action-icon" title="Active" href="<?php echo $this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'unpublish','id'=>$row->point_id),'',true);?>"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" title="Inactive" href="<?php echo $this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'publish','id'=>$row->point_id),'',true);?>"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
							?>
							
					   </td>
					   <td>
					   
							<a class="action-icon" title="Edit" href="<?php echo $this->url(array('module'=>'admin','controller'=>'pointssystem','action'=>'edit','id'=>$row->point_id),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
							
							<!--<a class="action-icon" title="Delete" href="<?php echo $this->url(array('module'=>'admin','controller'=>'faqs','action'=>'delete','id'=>$row->point_id),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
							
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="8">&nbsp;</td></tr>';
						echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->pageList,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">No Points Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>

<script type="text/javascript">

function set_sort_order(ajax_url,result_tab,tab_ajax)
{
	$.ajax({
	    type: "POST",
		url: ajax_url,
		async: false,
		data: "tab_ajax="+tab_ajax,
		success: function(result) {
			$('li#t1 a').removeClass('current');
			$('#tab1').hide();
			var b_array=result_tab.split('b');
			//alert(b_array[1]);
			$('li#t'+b_array[1]+' a').addClass('current');
			$('#'+result_tab).hide().html(result).fadeIn("slow");

		}
	});
	
	return false;
}

</script>