<?php 
$backUrl=$this->url(array('module'=>'company','controller'=>'auth','action'=>'index'),'',true);
$cancelUrl=$this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

?>
<style>
#form-add-user .heading {text-align:center;}
</style>
<div class="panel-content">

<div class="panel-sub-content">

	<div class="action-header">
		<span class="action-title">&nbsp;</span>
		<ul class="horizonal-menu">
			<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
		</ul>
	</div>

	<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
	<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
	<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
	<br  clear="all"/>
	<h3 class="company_head">Registration</h3>
		<form id="form-add-user" method="post" onsubmit="return validate_user('form-add-user');">
			<table align="center">
				<tr>
					<td align="center" valign="top">
					<h1>SignUp</h1>			
						
							<table align="left" width="400">
								<!--<tr>
									<td class="tdleftBold">User Type<span class="required">*</span> : </td>
									<td>
									    <select name="usertype" id="usertype">
										   <option value="">Select</option>
										   <option value="author" <?php if($formData["usertype"]=="author"){ ?> selected <?php } ?>>Author</option>
										   <option value="publisher"  <?php if($formData["usertype"]=="publisher"){ ?> selected <?php } ?>>Publisher</option>
										</select>
										
										 <?php if(array_key_exists('usertype',$formErrors)){echo '<div class="inline-error">'.$formErrors['usertype'].'</div>';}?>
										 
									</td>
								</tr>-->
								<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								</tr>
								<tr>
								<td colspan="2" class="heading"><strong>Personal Details</strong></td>
								</tr>		
								
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
								<tr>
									<td class="tdleftBold">Company Name<span class="required">*</span> : </td>
									<td>
										<input type="text" name="name" id="name" value="<?php if(isset($formData['name'])){echo $formData['name'];}?>"  class="req form-textfield"  message="Please enter company name."/>
										<?php if(array_key_exists('name',$formErrors)){echo '<div class="inline-error">'.$formErrors['name'].'</div>';}?>
									</td>
								</tr>
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
				
								<tr>
									<td class="tdleftBold">Email<span class="required">*</span> : </td>
									<td>
										<input type="text" name="user_email" id="user_email" value="<?php if(isset($formData['user_email'])){echo $formData['user_email'];}?>"  class="req validmail form-textfield" message="Please enter your email" invalidmessage="Please enter valid email address"/>
										<?php if(array_key_exists('user_email',$formErrors)){echo '<div class="inline-error">'.$formErrors['user_email'].'</div>';}?>
									</td>
								</tr>
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
								<tr>
									<td class="tdleftBold">Password<span class="required">*</span> : </td>
									<td>
										<input type="password" name="user_password" id="user_password" value="<?php if(isset($formData['user_password'])){echo $formData['user_password'];}?>" class="req pass form-textfield" message="Please enter password" />
										<?php if(array_key_exists('user_password',$formErrors)){echo '<div class="inline-error">'.$formErrors['user_password'].'</div>';}?>
									</td>
								</tr>
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
								
								<tr>
									<td class="tdleftBold">Country<span class="required">*</span> : </td>
									<td>
									
										<?php
										$modelPublisher = new Publisher_Model_DbTable_Publishers();
										$countryList=$modelPublisher->getCountryList();
										$formData["country"]=!empty($formData["country"])?$formData["country"]:0;
										?>
										
										<select name="country" id="country" class="req" message="Please select country">
										<option value="">Select Country</option>
										
										<?php
										for($ii=0;$ii<count($countryList);$ii++)
										{
										?>
										<option value="<?php echo $countryList[$ii]['id']; ?>" <?php if($formData["country"]==$countryList[$ii]["id"]){ ?> selected <?php } ?> ><?php echo $countryList[$ii]['country']; ?></option>
										<?php
										}
										?>		   
										</select>
										
									    <?php if(array_key_exists('country',$formErrors)){echo '<div class="inline-error">'.$formErrors['country'].'</div>';}?>

									</td>
								</tr>
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
								<tr>
									<td class="tdleftBold">State<span class="required">*</span> : </td>
									<td>
										<input type="text" name="state" id="state" value="<?php if(isset($formData['state'])){echo $formData['state'];}?>"  class="req form-textfield"  message="Please enter state" />
										<?php if(array_key_exists('state',$formErrors)){echo '<div class="inline-error">'.$formErrors['state'].'</div>';}?>
									</td>
								</tr>
								<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								</tr>
								<tr>
									<td class="tdleftBold">City<span class="required">*</span> : </td>
									<td>
										<input type="text" name="city" id="city" value="<?php if(isset($formData['city'])){echo $formData['city'];}?>"  class="req form-textfield"  message="Please enter city" />
										<?php if(array_key_exists('city',$formErrors)){echo '<div class="inline-error">'.$formErrors['city'].'</div>';}?>
									</td>
								</tr>
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
								<tr>
									<td class="tdleftBold">Phone<span class="required">*</span> : </td>
									<td>
										<input type="text" name="phone" id="phone" value="<?php if(isset($formData['phone'])){echo $formData['phone'];}?>" class="req pass form-textfield" message="Please enter phone number" />
										<?php if(array_key_exists('phone',$formErrors)){echo '<div class="inline-error">'.$formErrors['phone'].'</div>';}?>
									</td>
								</tr>
								<tr>
								<td colspan="2">&nbsp;</td>
								</tr>
								
								<tr>
									<td>&nbsp;</td>
									<td class="checkbox_div" colspan="2">
										<input type="checkbox" name="agree" id="agree" class="req" message="Please check agree" <?php if(isset($formData['agree'])){echo 'checked="checked"';}?>/><label>I agree to the </label><a href="#">Terms and Conditions</a>
										<?php if(array_key_exists('agree',$formErrors)){echo '<div class="inline-error">'.$formErrors['agree'].'</div>';}?>
									</td>
								</tr>								
								<tr>
									<td colspan="2">&nbsp;</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
									<td>
									<input type="submit" value="Register" class="button-Save"/>
									</td>
								</tr>
							 </table>
						       <table align="left" width="450">
								<tr>
									<td colspan="2" align="center" class="heading"><strong>Contact Details</strong> </td>
								</tr>
								<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								</tr>
                                <tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								</tr>
								<tr>
									<td class="tdleftBold">First name<span class="required">*</span> : </td>
									<td>
									<input type="text" name="first_name" id="first_name" value="<?php if(isset($formData['first_name'])){echo $formData['first_name'];}?>"  class="req form-textfield"  message="Please enter first name"/>
									<?php if(array_key_exists('first_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['first_name'].'</div>';}?>
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>				
								
								<tr>
									<td class="tdleftBold">Last Name<span class="required">*</span> : </td>
									<td>
										<input type="text" name="last_name" id="last_name" value="<?php if(isset($formData['last_name'])){echo $formData['last_name'];}?>"  class="req form-textfield"  message="Please enter last name" />
										<?php if(array_key_exists('last_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['last_name'].'</div>';}?>
									</td>
								</tr>						
								
								<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								</tr>								
								<!--<tr>
									<td class="tdleftBold">Pincode<span class="required">*</span> : </td>
									<td>
										<input type="text" name="pincode" id="pincode" value="<?php if(isset($formData['pincode'])){echo $formData['pincode'];}?>"  class="req form-textfield"  message="Please enter pincode" />
										<?php if(array_key_exists('pincode',$formErrors)){echo '<div class="inline-error">'.$formErrors['pincode'].'</div>';}?>
									</td>
								</tr>-->			
										
								<tr>
									<td class="tdleftBold">Phone : </td>
									<td>
										<input type="text" name="c_phone" id="c_phone" value="<?php if(isset($formData['phone'])){echo $formData['phone'];}?>"  class="req form-textfield"  message="Please enter phone" />
										<?php if(array_key_exists('c_phone',$formErrors)){echo '<div class="inline-error">'.$formErrors['c_phone'].'</div>';}?>
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>	
								<tr>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>
                                </table>		
					</td>
				</tr>
			</table>
		</form>
</div>
</div>

<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">

function validate_user(pFormId)
{
	
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	
	return true;
}
</script>
<?php /************END JAVASCRIPT CODE**************/?>

