<?php 
$groupObj = new Company_Model_DbTable_Groups();
?>
<div class="user_dashboard">
<?php include('leftnav.phtml');?>
</div>

<div class="welcome_user">
<div class="credithistory" style="width:100%">
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr>
	<td colspan="5" align="center"><h4>Group Publication</h4></td>
</tr>
<tr>
	<td colspan="5" height="25"></td>
</tr>
<tr>
	<td style="padding-bottom:8px;">
		<strong>S.No.</strong>
	</td>
		<td style="padding-bottom:8px;">
		<strong>Company Name</strong>
	</td>
	<td style="padding-bottom:8px;">
		<strong>Group Name</strong>
	</td>
	<td style="padding-bottom:8px;">
		<strong>Payment Status</strong>
	</td>
	<td style="padding-bottom:8px;">
		<strong>Purchase Date</strong>
	</td>
	<td>
		<strong>Action</strong>
	</td>
</tr>
<?php
$usersObj = new Model_DbTable_Companies();
 /*echo "<pre>";
 print_r($this->userdetails['first_name']." ".$this->userdetails['last_name']);
 echo "</pre>";*/
 
$j=1;
foreach($this->creditdata as $row)
{	
	$groupData =$groupObj->getInfoByGroupId($row['group_id']);
	$comname = $usersObj->fetchRow("id='".$row['userid']."'");
?>
<tr>
	<td style="padding-bottom:8px;">
		<?php echo $j;?>
	</td>
	<td style="padding-bottom:8px;">
		<?php echo stripslashes($comname['name']);?>
	</td>
	<td><?php echo $groupData['group_name'];?></td>
	<td style="padding-bottom:8px;">
		<?php
		if($row['payment_status'] == '1')
		{
			echo "Approved";
		}
		elseif($row['payment_status'] == '2')
		{
			echo "Declined";
		}
		else {
			echo "Incomplete";
		}
		?>
	</td>
	<td>
		<?php echo $row['add_date']; ?>
	</td>
	<td>
		<a class="action-icon" href="<?php echo $this->url(array('module'=>'user','controller'=>'index','action'=>'viewgrouppublication','orderid'=>$row['order_id']),'',true);?>" title="view order" ><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
	</td>
</tr>

<?php
$j++;}
?>

</table> 
</div>
<!--Payment History-->
</div>

