<?php
$cancelUrl=$this->url(array('module'=>'publisher','controller'=>'','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'publisher','controller'=>'','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

?>
<div id="panel">
	<div class="panel-header"><h3>Authors</h3><a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'add'),'',true);?>" title="Add New Author" onclick="return goToPage(this.href,'tab5','author');" class="addbook">Add Author</a></div>
	<div class="panel-content">
		<div class="panel-sub-content">
			
			<!--<div class="action-header">
				<span class="action-title">&nbsp;</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>-->	
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
			
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="20%" align="center">Name</th>
				   <th width="25%" align="center"><!--Username/-->Email Id</th>
				   <!--<th width="15%" align="center">Type</th>-->
				   <th width="10%" align="center">Phone</th>
				   <th width="10%" align="center">Added Date</th>
				   <th width="5%" align="center">Status</th>
				   <th width="10%" align="center">Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->authorList) && count($this->authorList)>0)
			  {
				$sNumber=1;
				foreach($this->authorList as $row)
				{
			?>
					<tr>
					<td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td><a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'view','id'=>$row['id']),'',true);?>" title="View Author" onclick="return goToPage(this.href,'tab5','author');"><?php echo $row['first_name']." ".$row['last_name'];?></a></td> 
					<td><?php 
					//echo $row['username']."<br>".$row['emailid'];
					echo $row['emailid'];
					?></td>
					<!--<td>
					<?php
					if(strtolower(trim($row['user_type'])) == strtolower(trim('Author')))
					{
						echo ucfirst(trim($row['user_type']));
					}
					else
					{
						echo"---";
					}
					   ?>
					</td>-->
					   <td><?php echo $row['phone'];?></td> 
					   <td><?php echo $row['add_time'];?></td>
					   <td>
						<?php 
						if($row['profile_status']=='1')
						{
						?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'inactive','id'=>$row['id']),'',true);?>" title="Click To Deactivate Author" onclick="return inactive(this.href,'tab5','author');"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
						<?php
						}
						else
						{
						?>
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'active','id'=>$row['id']),'',true);?>" title="Click To Activate Author" onclick="return active(this.href,'tab5','author');"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
						<?php
						}
						?>
						
					   </td>
					   <td>
					   
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'edit','id'=>$row['id']),'',true);?>" title="Edit Author" onclick="return goToPage(this.href,'tab5','author');"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
						
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'view','id'=>$row['id']),'',true);?>" title="View Author" onclick="return goToPage(this.href,'tab5','author');"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'author','action'=>'delete','id'=>$row['id']),'',true);?>" title="Delete Author" onclick="return deleteAction(this.href,'tab5','author');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>
						</td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax;
					$tab=5;$tab_ajax='author';
					
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->authorList,'Sliding','pagination.phtml').'</div></td></tr>';
					
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>	
	</div>
</div>
