<?php
//$addMemberUrl=$this->url(array('module'=>'company','controller'=>'member','action'=>'create'),'',true);

$addMemberUrl=$this->url(array('module'=>'company','controller'=>'member','action'=>'create'),'',true);

$cancelUrl=$this->url(array('module'=>'company','controller'=>'','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'company','controller'=>'member','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-3');";
}
elseif(isset($formData['tab_ajax']) && $formData['tab_ajax']=='mysetting')
{
$return_function="getSettingPanel('hide-3');";
}
else
{
	$return_function="goToPage('".$backUrl."','tab5','transactiontransactiontransactiontransaction');";
}
$modelBooks = new Publisher_Model_DbTable_Books();
$tab_ajax = 'transaction';
?>
<div id="panel">
	<div class="panel-header"><h3>Transaction History</h3><!--<a href="<?php echo $this->url(array('module'=>'company','controller'=>'Member','action'=>'create'),'',true);?>" title="Add New Member User" onclick="return goToPage(this.href,'tab3','Member');" class="addbook">Add Member User</a>--></div>
	<div class="panel-content" style="width:100%">
		<div class="panel-sub-content">
			
			<!--<div class="action-header">
				<span class="action-title">&nbsp;</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>-->	
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>	
	<br  clear="all"/>
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="20%" align="center">Order Id</th>
				   <th width="15%" align="center">Transaction Id</th>
				   <th width="25%" align="center">Purchased Date</th>				   
				   <th width="5%" align="center">Payment Status</th>
				   <!-- <th width="25%" align="center">View Xml</th>	
					<th width="25%" align="center">Print</th> -->
				   <th width="10%" align="center">Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->MemberList) && count($this->MemberList)>0)
			  {
				$sNumber=1;
				foreach($this->MemberList as $row)
				{
					$trans_history_data = $modelBooks->getAllProductTransactionById($row['transaction_id']);
			?>
					<tr>
					<td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td><a href="<?php echo $this->url(array('module'=>'company','controller'=>'transactionhistory','action'=>'view','orderid'=>$row['order_id']),'',true);?>" title="View Order" onclick="return goToPage(this.href,'tab6','transactionhistory');"><?php echo $row['order_id'];?></a></td> 
					
					<td><?php echo $row['transaction_id'];?></td>
					<td><?php echo $row['add_date'];?></td>					 
					   <td>
						<?php 
						if($row['payment_status'] == '1')
						{
						  echo "<strong>Completed</strong>";
						}
						elseif($row['payment_status'] == '2')
						{
						  echo "<strong>Declined</strong>"." (".$trans_history_data[0]['responseDescription'],")";
						}
						elseif($row['payment_status'] == '0'){
						 echo "<strong>Pending</strong>";
					   }
						?>
						
					   </td>
					  <!-- <td>
						<a href="javascript:void(0);" onClick="window.open('<?php echo $this->serverUrl().$this->baseUrl();?>/company/transactionhistory/viewxml/transid/<?php echo $row['transaction_id'];?>','name','height=700,width=500')" >View Xml</a>
					</td>
					<td>
						<a href="javascript:void(0);" onClick="window.open('<?php echo $this->serverUrl().$this->baseUrl();?>/company/transactionhistory/printtransaction/transid/<?php echo $row['transaction_id'];?>','name','height=700,width=500')" >Print</a>
					</td>-->
					   <td>
					   
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'transactionhistory','action'=>'view','orderid'=>$row['order_id']),'',true);?>" title="view order" onclick="return goToPage(this.href,'tab6','transactionhistory');"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
						</td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax; 
					$tab=6;$tab_ajax='transactionhistory';
					
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->MemberList,'Sliding','pagination.phtml').'</div></td></tr>';
					
					//echo '<tr><td colspan="8">&nbsp;</td></tr>';
					//echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->MemberList,'Sliding','ajax_pagination.phtml').'</div></td></tr>';
					
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>	
	</div>
</div>

