<?php
$producturrency = new Admin_Model_DbTable_Countries();
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
$this->modelPublisher = new Publisher_Model_DbTable_Publishers();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Transaction XML</h3></div>
	<div class="content-box-content">	
		<div>			
			<br style="clear: both;"/>				
				<table class="table-list" cellpadding="0" cellspacing="0">				
				<tr>
					<td>
					<?php
					//echo "<pre>";
					//print_r($this->trans_history_data);
						foreach($this->trans_history_data as $row)
						{
						?>
						<textarea rows='30' cols='50'><?php echo $row['transaction_xml'];?></textarea>
						<?php	
						}
					?>
					</td>
				</tr>
			 </table>
		</div>
	</div>
</div>