<?php
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>
<div id="panel">
	<div class="panel-header"> <h3 style="cursor: s-resize;">Sub-Admin Users Management</h3></div>
	<div class="panel-content">
		
		<div class="panel-sub-content">
		
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>

			<br style="clear: both;"/>	
			
			<form id="form-add-adminuser" name="form-add-adminuser" method="post" onsubmit="return validate_add_package('form-add-adminuser');">
			
			<table class="table-list" border="0" cellpadding="0" cellspacing="0" width="100%">
			   <tr>
					<td width="25%"></td>
					<td width="25%" valign="top" class="tdrightBold">Select Module<span class="required">*</span> :</td>
					<td width="25%">
					   <select name="modulename[]" id="modulename" multiple size="5" class="req form-selectfield"  message="Please select atleast one module" style="font-size:11px;"> 
					   <option value="">Select Modules</option>
						<?php
						if(isset($this->modleMenusList) && $this->modleMenusList>0)
						{
							foreach($this->modleMenusList as $key=>$detailArray)
							{
							?>
							<optgroup id="<?php echo $detailArray['id'];?>" label="<?php echo $detailArray['modulename'];?>">
							<?php
								if(!empty($detailArray['menu_ids']))
								{
									foreach($detailArray['menu_ids'] as $key=>$menuArray)
									{
										?>
										<option value="<?php echo $detailArray['menu_ids'][$key];?>"><?php echo $detailArray['menu_names'][$key];?></option>
										<?php
									}
								}
							?>
								
							</optgroup>	
							<?php	
							}
						}
						?>
					   </select>
					   <?php if(array_key_exists('modulename',$formErrors)){echo '<div class="inline-error">'.$formErrors['modulename'].'</div>';}?>
					</td>
					<td width="25%"></td>
			   </tr>
			   
				 <tr>
					<td width="25%"></td>
					<td width="25%" class="tdrightBold">First Name<span class="required">*</span> :</td>
					<td width="25%"><input type="text" name="firstname" id="firstname" class="req form-textfield"  message="Please enter first name"/>
					<?php if(array_key_exists('firstname',$formErrors)){echo '<div class="inline-error">'.$formErrors['firstname'].'</div>';}?>
					</td>
					<td width="25%"></td>
				</tr>
				 <tr>
					<td width="25%"></td>
					<td width="25%" class="tdrightBold">Last Name<span class="required">*</span> :</td>
					<td width="25%"><input type="text" name="lastname" id="lastname" class="req form-textfield" message="Please enter last name"/></td>
					<td width="25%"></td>
				</tr>
			    <tr>
					<td width="25%"></td>
					<td width="25%" class="tdrightBold">Username<span class="required">*</span> :</td>
					<td width="25%"><input type="text" name="username" id="username" class="req form-textfield" message="Please enter username"/></td>
					<td width="25%"></td>
			   </tr>
			    <tr>
					<td width="25%"></td>
					<td width="25%" class="tdrightBold">Password<span class="required">*</span> :</td>
					<td width="25%"><input type="text" name="password" id="password" class="req form-textfield" message="Please enter password"/></td>
					<td width="25%"></td>
			   </tr>
			    <tr>
					<td width="25%"></td>
					<td width="25%" class="tdrightBold">Email<span class="required">*</span> :</td>
					<td width="25%"><input type="text" name="email" id="email" class="req validmail form-textfield" message="Please enter email" invalidmessage="Please enter valid email"/></td>
					<td width="25%"></td>
			   </tr>
			    <tr>
					<td width="25%"></td>
					<td width="25%"></td>
					<td width="25%">
					<input type="submit" name="btnSubmit" value="Add User" class="button-Add"/> </td>
					<td width="25%"></td>
			   </tr>
			    <tr>
					<td width="25%">&nbsp;</td>
					<td width="25%">&nbsp;</td>
					<td width="25%">&nbsp;</td>
					<td width="25%">&nbsp;</td>
			   </tr>
			</table>
			</form>
			
			<br style="clear: both;"/>
			<form id="form-search" method="post">
			<!--<form id="form-search" method="post" onsubmit="return validate_search('form-search');">-->
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Users</th>
				</tr>
				
				 <tr>
					<td width="100%" colspan="8">
					Status:
					<select name="status" id="status" style="width:200px;">
					<option value="">Select Status</option>
					<option value="1" <?php if(isset($formData["status"]) && $formData["status"]=='1')echo"selected";?>>Active</option>
					<option value="0" <?php if(isset($formData["status"]) && $formData["status"]=='0')echo"selected";?>>Inactive</option>
					</select>
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add" title="Search">
					<input type="button" name="showall" value="Show All" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'adminusers','action'=>'index'),'',true);?>'" title="Show All"/>
					</td>
				</tr>
				</table>
			 </form>
			
			<br style="clear: both;"/>
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%">S.No</th>
				   <th width="20%">Name/Email Id</th>
				   <th width="40%">Modules</th>
				   <th width="10%">Username</th>
				  
				   <th width="5%">Status</th>
				   <th width="10%">Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->userList) && count($this->userList)>0)
			  {
				$sNumber=1;
				foreach($this->userList as $row)
				{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $row->first_name." ".$row->last_name;?><BR><?php echo $row->user_email;?></td> 
					   <td>
					   <?php
					   $modelModulesMenus = new Admin_Model_DbTable_ModulesMenus();
					   $modulesList=$modelModulesMenus->getModuleMenusList($row->modules);
					   //echo"<pre>";
					   //print_r($modulesList);
					   
					   foreach($modulesList as $key=>$accessArray)
					   {
							echo "<strong>".$modulesList[$key]['modulename']."</strong><br />";
							foreach($modulesList[$key]['menu_names'] as $menu_name)
							{
								echo "&nbsp;&nbsp;&nbsp;&nbsp;<strong><font color='green'>".$menu_name."</font></strong><br />";
							}
							echo"<br />";
					   }
					   ?>
					   </td>
					   <td><?php echo $row->user_name;?></td> 
					 
					   <td>
							<?php 
							if($row->is_active=='1')
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminusers','action'=>'inactive','id'=>$row->id),'',true);?>" title="Active"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminusers','action'=>'active','id'=>$row->id),'',true);?>" title="Inactive"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
							?>
						
					   </td>
					   <td>
					   
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminusers','action'=>'edit','id'=>$row->id),'',true);?>" title="Edit"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
						
					<!--	<a class="action-icon" title="View" href="<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'view','id'=>$row->id),'',true);?>"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>-->
							
							<!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'adminusers','action'=>'delete','id'=>$row->id),'',true);?>" title="Delete" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
							
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->userList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>

<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">
function validate_add_package(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>
<?php /************END JAVASCRIPT CODE**************/?>