<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'profile','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'profile','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize; text-decoration:none;">My Profile</h3></div>
	<div class="content-box-content">
	
		<div>
			<div class="action-header">
				<span class="action-title">Edit Page</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br  clear="all"/>
			
			<form id="form-change-password" method="post" onsubmit="return validate_change_password('form-change-password');">
				
				<table class="table-form" cellpadding="0" cellspacing="0">
					<tr>
						<td width="25%" class="tdrightBold">Old Password<span class="required">*</span> : </td>
						<td>
							<input type="password" name="user_password" id="user_password" value="<?php if(isset($formData['user_password'])){echo $formData['user_password'];}?>" class="req form-textfield" class="req text-input user_name"  message="Please enter your current password"  invalidmessage="Please enter your current password"/>
							<?php if(array_key_exists('user_password',$formErrors)){echo '<div class="inline-error">'.$formErrors['user_password'].'</div>';}?>
						</td>
					</tr>
					<tr>
						<td width="25%" class="tdrightBold">New Password<span class="required">*</span> : </td>
						<td>
							<input type="password" name="new_password" id="new_password" value="<?php if(isset($formData['new_password'])){echo $formData['new_password'];}?>" class="req form-textfield"  message="Please enter your new password"  invalidmessage="Please enter your new password"/>
							<?php if(array_key_exists('new_password',$formErrors)){echo '<div class="inline-error">'.$formErrors['new_password'].'</div>';}?>
						</td>
					</tr>
					<tr>
						<td width="20%" class="tdrightBold">Confirm New Password<span class="required">*</span> : </td>
						<td>
							<input type="password" name="conf_new_password" id="conf_new_password" value="<?php if(isset($formData['conf_new_password'])){echo $formData['conf_new_password'];}?>" class="req form-textfield"  message="Please confirm your new password"  invalidmessage="Confirm password does not match"/>
							<?php if(array_key_exists('conf_new_password',$formErrors)){echo '<div class="inline-error">'.$formErrors['conf_new_password'].'</div>';}?>
						</td>
					</tr>
					<tr>
						<td width="25%" class="tdrightBold">&nbsp;</td>
						<td>
							<input type="submit" value="Save" class="button-Save" title="Save" />
							<input type="button" value="Cancel" name="btnCancel" class="button-cancel" onclick="window.location.href='<?php echo $cancelUrl;?>';" title="Cancel"/>
						</td>
					</tr>
				  
				 </table>
			</form>
	</div>
</div>

<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">
function validate_change_password(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>
<?php /************END JAVASCRIPT CODE**************/?>