<?php

$addGroupUrl=$this->url(array('module'=>'company','controller'=>'group','action'=>'create'),'',true);

$cancelUrl=$this->url(array('module'=>'company','controller'=>'','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'company','controller'=>'group','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-3');";
}
elseif(isset($formData['tab_ajax']) && $formData['tab_ajax']=='mysetting')
{
$return_function="getSettingPanel('hide-3');";
}
else
{
	$return_function="goToPage('".$backUrl."','tab5','group');";
}
?>
<div id="panel">
	<div class="panel-header"><h3>Manage Groups</h3><!--<a href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'create'),'',true);?>" title="Add New group Group" onclick="return goToPage(this.href,'tab5','group');" class="addbook">Add group Group</a>--></div>
	<div class="panel-content">
		<div class="panel-sub-content">
			
			<!--<div class="action-header">
				<span class="action-title">&nbsp;</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>-->	
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
		
		<form id="form-add-group" method="post" onsubmit="return validate_common_form('form-add-group','<?php echo $addGroupUrl;?>','tab5');">
		<table cellpadding="0" cellspacing="0">
			
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td class="tdleftBold">
				Group name<span class="required">*</span> : 
				</td>
				<td>
					<input type="text" name="group_name" id="group_name" value="<?php if(isset($formData['group_name'])){echo $formData['group_name'];}?>"  class="req form-textfield"  message="Please enter group name"/>
					<?php if(array_key_exists('group_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['group_name'].'</div>';}?>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="tdleftBold">&nbsp;</td>
				<td>
					<input type="hidden" name="create_group" value="Create">
					<input type="submit" value="Create" title="Create Group" class="button-Save" />
				</td>
			</tr>
		</table>
					
	</form>
	
	<br  clear="all"/>
			
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="20%" align="center">Name</th>
				   <th width="20%" align="center">Created On</th>
				   <th width="20%" align="center">Updated On</th>
				   <th width="5%" align="center">Status</th>
				   <th width="10%" align="center">Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->GroupList) && count($this->GroupList)>0)
			  {
				$sNumber=1;
				foreach($this->GroupList as $row)
				{
			?>
					<tr>
					<td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td><a href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'edit','id'=>$row['id']),'',true);?>" title="View" onclick="return goToPage(this.href,'tab5','group');"><?php echo $row['group_name'];?></a></td> 
					<td><?php echo $row['created_date'];?></td>
					   <td><?php echo $row['updated_date'];?></td>
					   <td>
						<?php 
						if($row['status']=='1')
						{
						?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'inactive','id'=>$row['id']),'',true);?>" title="Click To Deactivate Group" onclick="return inactive(this.href,'tab5','group');"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/images/active.png"/></a>
						<?php
						}
						else
						{
						?>
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'active','id'=>$row['id']),'',true);?>" title="Click To Activate Group" onclick="return active(this.href,'tab5','group');"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/images/inactive.png"/></a>
						<?php
						}
						?>
						
					   </td>
					   <td>
					   
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'edit','id'=>$row['id']),'',true);?>" title="Edit Group" onclick="return goToPage(this.href,'tab5','group');"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/images/icon_edit.png"/></a>
						
						<!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'view','id'=>$row['id']),'',true);?>" title="View Group" onclick="return goToPage(this.href,'tab5','group');"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>-->
							
						<?php
						$modelCompany = new Company_Model_DbTable_Companies();
						$memberList=$modelCompany->getMemberByGroupId($row['id']);
						
						$modelGroupSubscription = new Company_Model_DbTable_GroupSubscriptions();
						$groupSubscriptionList=$modelGroupSubscription->getSubscriptionList($row['id']);
						
						if(count($groupSubscriptionList)>0)
						{
						?>
						<a class="action-icon" href="javascript:void(0);" title="Delete Group" onclick="javascript:alert('Delete all it\'s subscriptions first!'); return false;"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/images/trash.gif"/></a>
						<?php
						}
						elseif(count($memberList)>0)
						{
						?>
						<a class="action-icon" href="javascript:void(0);" title="Delete Group" onclick="javascript:alert('Delete all it\'s members first!'); return false;"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/images/trash.gif"/></a>
						<?php
						}
						else
						{
						?>
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'company','controller'=>'group','action'=>'delete','id'=>$row['id']),'',true);?>" title="Delete Group" onclick="return deleteAction(this.href,'tab5','group');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/images/trash.gif"/></a>
						<?php
						}
						?>
						</td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax; 
					$tab=5;$tab_ajax='group';
					
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->GroupList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>	
	</div>
</div>

