<?php
$formData=(isset($this->formData))?$this->formData:array();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Publication Management</h3></div>
	<div class="content-box-content">
	
		<div>

			<br style="clear: both;"/>
			<div class="action-header">
				<span class="action-title">Publication List</span>
				<!--<ul class="horizonal-menu">
					<li class="add"><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'add'),'',true);?>">Add Category</a></li>
				</ul>-->
			</div>
			<br style="clear: both;"/>	
			
			<form id="form-search" method="post" onsubmit="return validate_search('form-search');">
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Publications</th>
				</tr>
				
				 <tr>
					<td width="100%" colspan="8">Title / Brand:<input type="text" name="searchword" id="searchword" value="<?php if(isset($formData["searchword"]) && !empty($formData["searchword"])) echo $formData["searchword"]; ?>" style="width:120px;"> Genre:
					<?php
					$modelGenre = new Publisher_Model_DbTable_Genres();
					$genreList=$modelGenre->getGenreList();
					?>
					<select name="booktype" id="booktype" style="width:120px;">
					<option value="">Select Genre</option>
					<?php
					for($ii=0;$ii<count($genreList);$ii++)
					{
					?>
					<option value="<?php echo $genreList[$ii]['id']; ?>" <?php if(isset($formData["booktype"]) && $formData["booktype"]==$genreList[$ii]["id"]){ ?> selected <?php } ?> ><?php echo $genreList[$ii]['genre']; ?></option>
					<?php
					}
					?>	
					</select>
					ISBN / ISSN:<input type="text" name="searchisbn" id="searchisbn" value="<?php if(isset($formData["searchisbn"]) && !empty($formData["searchisbn"])) echo $formData["searchisbn"]; ?>" style="width:120px;">
					
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add" title="Search">
					<input type="button" name="showall" value="Show All" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'index'),'',true);?>'" title="Show All"/>
					</td>
				</tr>
				</table>
			 </form>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			<br style="clear: both;"/>	
			
			<form name="frm" id="frm" action="" enctype="multipart/form-data" method="post">
			<table class="table-list" cellpadding="0" cellspacing="0">
			   <tr>
				   <th>SL.No</th>
				   <!--<th>ID</th>-->
				   <th>Title / Brand</th>
				   <th>Genre</th>
				   <th>Author / Publisher</th>
				   <th>ISBN / ISSN</th>
				   <th>Publish Time</th>
				   <th>Status</th>
				   <th>
				   <input type="submit" name="featuredbutton" id="featuredbutton" value="Set Featured" style="font-size:11px; height:5px;"/><BR />
				    <input type="submit" name="unfeaturedbutton" id="unfeaturedbutton" value="Unset Featured" style="font-size:11px; height:5px;"/>
				   </th>
				   <th>Action</th>
			   </tr>
			<?php 
			  if(isset($this->prodList) && count($this->prodList)>0)
			  {
				$sNumber=1;
				foreach($this->prodList as $row)
				{
				
				$issuesList=$this->modelIssue->getList(0,$row->id);
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <!--<td><?php echo $row->id;?></td>--> 
					   <td>
					   <?php
					   $modelCategory = new Publisher_Model_DbTable_Books();
					   $getBrandInfo=$modelCategory->getBrandInfo($row->title);
					   if(!empty($getBrandInfo))
					   {
							$titleBrand=$getBrandInfo['brand'];
					   }else
					   {
							$titleBrand=$row->title;
					   }
						if(!empty($row->parent_brand_id))
						{
						$productInfo=$this->modelPublications->fetchRow('id='.$row->parent_brand_id);
						$getParentBrandInfo=$modelCategory->getBrandInfo($productInfo->title);
							if(!empty($getParentBrandInfo))
							{
								$titleBrand=$titleBrand.' ('.$getParentBrandInfo['brand'].')';
							}
						}
						
					   echo $titleBrand;
						?></td>
					   <td>
					   <?php
					   //echo $row->product_type;
					   $genreInfo=$this->modelGenre->getGenreInfo($row->product_type);
					   echo $genreInfo['genre'];?></td>
					   <td><?php $this->modelPublications=new Admin_Model_DbTable_Publications();
					   $publisher_info_array=$this->modelPublications->getPublisherInfo($row->author_id);
					   if(!empty($publisher_info_array))
					   {
					   echo $publisher_info_array['first_name']."&nbsp;".$publisher_info_array['last_name'];
					   }
					   else
					   {
						echo $row->publisher;
					   }
					   
					   ?></td>	   
					   <td><?php echo $row->isbn_number; ?></td>
					   <td><?php echo CommonFunctions::formatDate($row->publish_time); ?></td>
					   <td>
						<?php 
							if($row->admin_approve=='1')
							{
							?>
							<a class="action-icon" title="Active" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'inactive','id'=>$row->id),'',true);?>"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" title="Inactive" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'active','id'=>$row->id),'',true);?>"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
							?>
						<!---->
						
					   </td>
					   <td align="center" style="text-align:center;">
						<?php 
						if($row->is_featured=='1')
						{
						?>
						<input type="checkbox" name="is_featured[]" id="is_featured[]" value="<?php echo $row->id; ?>" checked="checked">
						<?php
						}
						else
						{
						?>
						<input type="checkbox" name="is_featured[]" id="is_featured[]" value="<?php echo $row->id; ?>">
						<?php
						}
						?>
					   </td>
					   <td>
							<!--<a class="action-icon" title="Edit" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'edit','id'=>$row->id),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>-->
							
							<?php
							if(!empty($issuesList) && count($issuesList)>0)
							{
							?>
							<a class="action-icon" title="View And Manage Issues" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'issues','parentid'=>$row->id),'',true);?>"><img alt="View And Manage Issues" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							<?php
							}
							else
							{
							?>
							<a class="action-icon" title="View" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'view','id'=>$row->id),'',true);?>"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							<?php
							}
							?>
							
							<!--<a class="action-icon" title="Delete" href="<?php echo $this->url(array('module'=>'admin','controller'=>'publications','action'=>'delete','id'=>$row->id),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="9">&nbsp;</td></tr>';
						echo '<tr><td colspan="9"><div class="pagination">'.$this->paginationControl($this->prodList,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="9" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
			</form>
		</div>

	</div>
</div>

<script type="text/javascript">
function validate_search(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>