<?php
$formData=(isset($this->formData))?$this->formData:array();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Enquiry Management</h3></div>
	<div class="content-box-content">
		
		<form id="form-search" method="post" onsubmit="return validate_search('form-search');">
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Enquiries</th>
				</tr>
				
				 <tr>
					<td width="100%" colspan="8">
					<!--User Permission:<select name="user_permission" id="user_permission" style="width:200px;">
					<option value="">Select Permission</option>
					<option value="1" <?php if(isset($formData["user_permission"]) && $formData["user_permission"]==1)echo"selected";?>>Yes</option>
					<option value="0" <?php if(isset($formData["user_permission"]) && $formData["user_permission"]==0)echo"selected";?>>No</option>
					</select>--> 
					Status:
					<select name="status" id="status" style="width:200px;">
					<option value="">Select Status</option>
					<option value="pending" <?php if(isset($formData["status"]) && $formData["status"]=='pending')echo"selected";?>>Pending</option>
					<option value="replied" <?php if(isset($formData["status"]) && $formData["status"]=='replied')echo"selected";?>>Replied</option>
					</select>
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add" title="Search">
					<input type="button" name="showall" value="Show All" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'enquirys','action'=>'index'),'',true);?>'" title="Show All"/>
					<div style="float:right;"><input type="button" name="export_csv" id="export_csv" value="Export Enquiries" class="button-Add" title="Export Enquiries" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'enquirys','action'=>'exportenquiries'),'',true);?>'"></div>
					</td>
				</tr>
				</table>
			 </form>
		
		<div>
		
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br style="clear: both;"/>	
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th>S.No</th>
				   <th>Name</th>
				   <th>Email Id</th>
				   <th>Phone</th>
				   <th>Date</th>
				   <th>User Permission</th>
				   <th>Status</th>
				   <th>Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->enquiryList) && count($this->enquiryList)>0)
			  {
				$sNumber=1;
				foreach($this->enquiryList as $row)
				{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $row->name ;?></td> 
					   <td><?php echo $row->email;?></td>
					   <td><?php echo $row->phone;?></td> 
					   <td><?php echo $row->add_time;?></td>
					   <td><?php echo ($row->user_permission==1)?'Yes':'No';?></td>
					   <td><?php echo ucfirst($row->status);?></td>
					   <td>
					        <a class="action-icon" title="View" href="<?php echo $this->url(array('module'=>'admin','controller'=>'enquirys','action'=>'view','id'=>$row->id),'',true);?>"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							
							<!--<a class="action-icon" title="Delete" href="<?php echo $this->url(array('module'=>'admin','controller'=>'enquirys','action'=>'delete','id'=>$row->id),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
							
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->enquiryList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>