<?php
$formData=(isset($this->formData))?$this->formData:array();
//$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Users Management</h3></div>
	<div class="content-box-content">
	
		<div>
		
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br style="clear: both;"/>
			<form id="form-search" method="post">
			<!--<form id="form-search" method="post" onsubmit="return validate_search('form-search');">-->
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Users</th>
				</tr>
				
				 <tr>
					<td width="100%" colspan="8">
					Status:
					<select name="status" id="status" style="width:200px;">
					<option value="">Select Status</option>
					<option value="1" <?php if(isset($formData["status"]) && $formData["status"]=='1')echo"selected";?>>Active</option>
					<option value="0" <?php if(isset($formData["status"]) && $formData["status"]=='0')echo"selected";?>>Inactive</option>
					</select>
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add" title="Search">
					<input type="button" name="showall" value="Show All" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'index'),'',true);?>'" title="Show All"/>
					
					<input type="button" name="showall" value="Export" class="button-Add" onclick="javascript:document.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'exportusercsv',"type"=>$formData["status"]),'',true);?>'" title="Show All"/></td>
				</tr>
				</table>
			 </form>
			<br style="clear: both;"/>	
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th>S.No</th>
				    <th>User Id</th>
				   <th>Name</th>
				   <th>Username</th>
				   <th>Account Type</th>
				   <th>Phone</th>
				   <th>Join Date</th>
				   <th>Status</th>
				   <th>Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->userList) && count($this->userList)>0)
			  {
				$sNumber=1;
				foreach($this->userList as $row)
				{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $row->id;?></td> 
					   <td><?php echo $row->first_name." ".$row->last_name;?></td> 
					   <td><?php echo $row->user_email;?></td>
					   <td><?php if($row->account_type==1) echo"Company";elseif($row->account_type==2)echo"Individual";else echo"Undefined";?></td>
					   <td><?php echo $row->phone;?></td> 
					   <td><?php echo $row->added_date;?></td>
					   <td>
							<?php 
							if($row->status=='1')
							{
							?>
							<a class="action-icon" title="Inactive" href="<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'inactive','id'=>$row->id),'',true);?>"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" title="Active" href="<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'active','id'=>$row->id),'',true);?>"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
							?>
						
					   </td>
					   <td>
					   
						<!--	<a class="action-icon" title="Edit" href="<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'edit','id'=>$row->id),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>-->
						
						<a class="action-icon" title="View" href="<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'view','id'=>$row->id),'',true);?>"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							
							<!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'users','action'=>'delete','id'=>$row->id),'',true);?>" title="Delete" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
							
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->userList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>