<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'users','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'users','action'=>'index'),'',true);

$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>

<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Users Management</h3></div>
	<div class="content-box-content">
	
		<div>
			<div class="action-header">
				<span class="action-title">Users Details</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
				</ul>
			</div>
		
			<br  clear="all"/>
			
<table class="table-form" cellpadding="0" cellspacing="0">

<!--<tr>
<td width="20%" class="tdrightBold">Username </td>
<td><?php echo $formData['user_name']; ?></td>
</tr>-->
<tr>
<td width="20%" class="tdrightBold">Username</td>
<td><?php echo $formData['user_email']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Name </td>
<td><?php echo $formData['first_name']." ".$formData['last_name']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Account Type: </td>
<td><?php if($formData['account_type']==1)echo"Company";elseif($formData['account_type']==2)echo"Individual"; else echo"Undefined"; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Country: </td>
<td><?php
$countryModel=new Admin_Model_DbTable_Users();
$countryInfo=$countryModel->getCountryInfo($formData['country']);
echo $countryInfo['country']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Phone: </td>
<td><?php echo $formData['phone']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Join Date: </td>
<td><?php echo $formData['added_date']; ?></td>
</tr>

</table>
			
</div>

