<?php 
$currUrl=$this->url();
$cancelUrl=$this->url(array('module'=>'publisher','controller'=>'group','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'publisher','controller'=>'group','action'=>'index'),'',true);

$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

if(isset($formData['tab_ajax']) && $formData['tab_ajax']=='dashboard')
{
$return_function="getDashboard('hide-3');";
}
elseif(isset($formData['tab_ajax']) && $formData['tab_ajax']=='mysetting')
{
$return_function="getSettingPanel('hide-3');";
}
else
{
	$return_function="goToPage('".$backUrl."','tab3','group');";
}
?>

<div id="panel">
	<div class="panel-header"><h3>Add Group User</h3></div>
	<div class="panel-content">
		<div class="panel-sub-content">
		
		<div class="action-header">
			<span class="action-title">&nbsp;</span>
			<ul class="horizonal-menu">
				<li class="back"><a href="<?php echo $backUrl;?>" title="Back" onclick="return <?php echo $return_function;?>">Back</a></li>
			</ul>
		</div>
		
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br clear="all"/>

		<form id="form-add-group-user" method="post" onsubmit="return validate_common_form('form-add-group-user','<?php echo $currUrl;?>','tab3');">
		<table cellpadding="0" cellspacing="0">
			<tr>
				<td class="tdleftBold">
				Type<span class="required">*</span> : 
				</td>
				<td>
				    <select name="user_type" id="user_type" class="req" message="Please select a type">
					   <option value="">Select</option>
					   <option value="Pmanager" <?php if($formData["user_type"]=="Pmanager"){ ?> selected <?php } ?>>Publication Manager</option>
					   <option value="Amanager"  <?php if($formData["user_type"]=="Amanager"){ ?> selected <?php } ?>>Account Manager</option>
					</select>
					<?php if(array_key_exists('user_type',$formErrors)){echo '<div class="inline-error">'.$formErrors['user_type'].'</div>';}?>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td class="tdleftBold">
				First name<span class="required">*</span> : 
				</td>
				<td>
					<input type="text" name="first_name" id="first_name" value="<?php if(isset($formData['first_name'])){echo $formData['first_name'];}?>"  class="req form-textfield"  message="Please enter first name"/>
					<?php if(array_key_exists('first_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['first_name'].'</div>';}?>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td class="tdleftBold">
				Last Name<span class="required">*</span> : 
				</td>
				<td>
					<input type="text" name="last_name" id="last_name" value="<?php if(isset($formData['last_name'])){echo $formData['last_name'];}?>"  class="req form-textfield"  message="Please enter last name" />
					<?php if(array_key_exists('last_name',$formErrors)){echo '<div class="inline-error">'.$formErrors['last_name'].'</div>';}?>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>					
			<tr>
				<td class="tdleftBold">
				Email<span class="required">*</span> : 
				</td>
				<td>
					<input type="text" name="emailid" id="emailid" value="<?php if(isset($formData['emailid'])){echo $formData['emailid'];}?>"  class="req validmail form-textfield" message="Please enter your email" invalidmessage="Please enter valid email address"/>
					<?php if(array_key_exists('emailid',$formErrors)){echo '<div class="inline-error">'.$formErrors['emailid'].'</div>';}?>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>					
		<!--<tr>
				<td class="tdleftBold">
				Password<span class="required">*</span> : 
				</td>
				<td>
					<input type="password" name="password" id="password" value="<?php if(isset($formData['password'])){echo $formData['password'];}?>" class="req pass form-textfield" message="Please enter password" />
					<?php if(array_key_exists('password',$formErrors)){echo '<div class="inline-error">'.$formErrors['password'].'</div>';}?>
				</td>
			</tr>-->
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>					
			<tr>
				<td class="tdleftBold">Phone : </td>
				<td>
					<input type="text" name="phone" id="phone" value="<?php if(isset($formData['phone'])){echo $formData['phone'];}?>"  class="number form-textfield"  invalidmessage="Please enter numeric value" />
					<?php if(array_key_exists('phone',$formErrors)){echo '<div class="inline-error">'.$formErrors['phone'].'</div>';}?>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>					
			<tr>
				<td class="tdleftBold">&nbsp;</td>
				<td>
					<input type="hidden" name="create_group" value="Create">
					<input type="submit" value="Add" title="Add User" class="button-Save" />
					<input type="button" value="Cancel" name="btnCancel" title="Cancel" class="button-cancel" onclick="return <?php echo $return_function;?>" />
				</td>
			</tr>
		</table>
					
	</form>
	</div>
</div>	
</div>

