<?php
$cancelUrl=$this->url(array('module'=>'publisher','controller'=>'','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'publisher','controller'=>'','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
$currUrl=$this->url(array('module'=>'publisher','controller'=>'group','action'=>'index'),'',true);

?>
<div id="panel">
	<div class="panel-header"><h3>My Group Users</h3><a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'create'),'',true);?>" title="Add New Group User" onclick="return goToPage(this.href,'tab3','group');" class="addbook">Add Group User</a></div>
	<div class="panel-content">
		<div class="panel-sub-content">
			<form name="form-search" id="form-search" method="post" onsubmit="return validate_common_form('form-search','<?php echo $currUrl;?>','tab3');">
				<table class="table-list" cellpadding="0" cellspacing="0">
				<tr>
					<th colspan="2">Search Publications</th>
				</tr>				
				 <tr>
					<td width="100%" colspan="8">Search:<input type="text" name="searchword" id="searchword" value="<?php if(isset($formData["searchword"]) && !empty($formData["searchword"])) echo $formData["searchword"]; ?>" style="width:225px;">					
					<input type="submit" name="searchresult" id="searchresult" value="Search"  class="button-Add">
					
					</td>
				</tr>
				</table>
			 </form>
			<!--<div class="action-header">
				<span class="action-title">&nbsp;</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>-->	
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
			
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="20%" align="center">Name</th>
				   <th width="25%" align="center">Email Id</th>
				   <th width="15%" align="center">Group</th>
				   <th width="10%" align="center">Phone</th>
				   <th width="10%" align="center">Join Date</th>
				   <th width="5%" align="center">Status</th>
				   <th width="10%" align="center">Action</th>
			   </tr>
			   
			<?php 
			  
			  if(isset($this->groupList) && count($this->groupList)>0)
			  {
				$sNumber=1;
				foreach($this->groupList as $row)
				{
			?>
					<tr>
					<td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td><a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'view','id'=>$row['id']),'',true);?>" title="View User" onclick="return goToPage(this.href,'tab3','group');"><?php echo $row['first_name']." ".$row['last_name'];?></a></td> 
					<td><?php echo $row['emailid'];?></td>
					<td>
					<?php
					if(strtolower(trim($row['user_type'])) == strtolower(trim('Pmanager')))
					{
						echo "Publication Manager";
					}
					elseif(strtolower(trim($row['user_type'])) == strtolower(trim('Amanager')))
					{
						echo "Account Manager";
					}
					else
					{
						echo"---";
					}
					   ?>
					   </td>
					   <td><?php echo $row['phone'];?></td> 
					   <td><?php echo $row['add_time'];?></td>
					   <td>
						<?php 
						if($row['profile_status']=='1')
						{
						?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'inactive','id'=>$row['id']),'',true);?>" title="Click To Deactivate User" onclick="return inactive(this.href,'tab3','group');"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
						<?php
						}
						else
						{
						?>
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'active','id'=>$row['id']),'',true);?>" title="Click To Activate User" onclick="return active(this.href,'tab3','group');"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
						<?php
						}
						?>
						
					   </td>
					   <td>
					   
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'edit','id'=>$row['id']),'',true);?>" title="Edit User" onclick="return goToPage(this.href,'tab3','group');"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
						
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'view','id'=>$row['id']),'',true);?>" title="View User" onclick="return goToPage(this.href,'tab3','group');"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
							
						<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'group','action'=>'delete','id'=>$row['id']),'',true);?>" title="Delete User" onclick="return deleteAction(this.href,'tab3','group');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>
						</td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax;
					$tab=3; $tab_ajax='group';
					
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->groupList,'Sliding','pagination.phtml').'</div></td></tr>';
					
					//echo '<tr><td colspan="8">&nbsp;</td></tr>';
					//echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->groupList,'Sliding','ajax_pagination.phtml').'</div></td></tr>';
					
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>	
	</div>
</div>

