<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'reviews','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'reviews','action'=>'index'),'',true);

$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
 $this->modelBooks = new Publisher_Model_DbTable_Books();
// print_r($formData);
  $product_details = $this->modelBooks->fetchRow("id='".$formData['productid']."'");
 $getBrandInfo=$this->modelBooks->getBrandInfo($product_details['title']);
	if(!empty($getBrandInfo) && is_numeric($this->$product_details['title']))
	{
		$titleBrand=$getBrandInfo['brand'];
	}
	else
	{
		$titleBrand=$product_details['title'];
	}
	if(!empty($product_details['parent_brand_id']) && $product_details['cat_id']!='3')
	{
		$productInfo=$this->modelBooks->fetchRow('id="'.$product_details['parent_brand_id'].'"');
		$getParentBrandInfo=$this->modelBooks->getBrandInfo($productInfo->title);
		if(!empty($getParentBrandInfo))
		{
			//$titleBrand=$titleBrand.' ('.$getParentBrandInfo['brand'].')';
			$titleBrand=$getParentBrandInfo['brand']." - ".$titleBrand;
		}				
	}
?>

<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Reviews Management</h3></div>
	<div class="content-box-content">
	
		<div>
			<div class="action-header">
				<span class="action-title">Review Details</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>" title="Back">Back</a></li>
				</ul>
			</div>
		
			<br  clear="all"/>
			
<table class="table-form" cellpadding="0" cellspacing="0">

<tr>
<td width="20%" class="tdrightBold">Publication </td>
<td><?php echo stripslashes($titleBrand); ?></td>
</tr>
<tr>
<tr>
<td width="20%" class="tdrightBold">Name </td>
<td><?php echo $formData['name']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Email </td>
<td><?php echo $formData['email']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Rating </td>
<td>
<?php
for($ii=0; $ii<$formData['rating']; $ii++)
{
?>
<img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/star.png"/>
<?php
}
?>
</td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Comments: </td>
<td><?php echo $formData['comments']; ?></td>
</tr>
<tr>
<td width="20%" class="tdrightBold">Date: </td>
<td><?php echo $formData['add_time']; ?></td>
</tr>

</table>
			
</div>

