<?php 
$cancelUrl=$this->url(array('module'=>'user','controller'=>'auth','action'=>'index'),'',true);
$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
?>

<div id="login">
		<div class="login-header">Forgot Password</div>
		
		<div class="login-content">
			<br clear="all"/>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<form name="form-forgotpassword" id="form-forgotpassword" action="" method="post" onsubmit="return validate_login('form-forgotpassword');">
			
				<table style="margin:20px auto;">
					<tr>
						<td>Email-Id<span class="required">*</span>	:</td>
						<td><input type="text" name="email_id" id="email_id" value="<?php if(isset($formData['email_id'])){echo $formData['email_id'];}?>" class="req validmail form-textfield" message="Please enter your email" invalidmessage="Please enter valid email address"/> 
						<?php if(array_key_exists('email_id',$formErrors)){echo '<div class="inline-error">'.$formErrors['email_id'].'</div>';}?>
						
						</td>
					</tr>
					
					<tr>
						<td colspan="2" style="text-align:right;">
							<input type="submit" value="Submit" name="btnLogin" class="btnLogin"/>
						</td>
					</tr>
				</table>
			</form>
		</div>
	</div>
	
<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">
function validate_login(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	
	return true;
}
</script>
<?php /************END JAVASCRIPT CODE**************/?>	