<?php
$backUrl=$this->url(array('module'=>'publisher','controller'=>'book','action'=>'index'),'',true);

$createUrl=$this->url(array('module'=>'publisher','controller'=>'issues','action'=>'create','parentid'=>$this->ParentPublicationInfo['id']),'',true);
$issueList=(isset($this->issueList))?$this->issueList:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();
$formData=(isset($this->formData))?$this->formData:array();
?>

<div id="panel">
	<div class="panel-header">
	    <h3>Publication Brand: <?php echo $this->ParentBrandInfo['brand'];?></h3>
	    <a href="<?php echo $createUrl;?>" onclick="return goToPage(this.href,'tab2','issue');" title="Create New Issue" class="addbook">Create New Issue</a>
	</div>
	
	<div class="panel-content" id="addissue">
		<div class="panel-sub-content" >
		
		<div class="action-header">
		<span class="action-title">&nbsp;</span>
		<ul class="horizonal-menu">
		<li class="back"><a href="<?php echo $backUrl;?>" title="Back" onclick="return goToPage(this.href,'tab2','book');">Back</a></li>
		</ul>
		</div>
		
		<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
		<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
		<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
		
		<br  clear="all"/>
			
			<table class="table-list" cellpadding="0" cellspacing="0" width="100%">
			
			   <tr>
				   <th width="5%" align="center">S.No</th>
				   <th width="15%" align="center">Title</th>
				   <th width="15%" align="center">Genre</th>
				   <th width="15%" align="center">Type</th>
				   <th width="15%" align="center">Edition</th>
				   <th width="15%" align="center">Issue Date</th>
				   <?php
					if(strtolower(trim($this->sessPublisherInfo->user_type))==strtolower(trim('publisher')))
					{
					?>
					<th width="5%" align="center">Status</th>
					<?php
					}
					?>
				   <th width="10%" align="center">Action</th>
			   </tr>
			   
			<?php 
						   
			  if(isset($this->issueList) && count($this->issueList)>0)
			  { 
				$sNumber=1;
				foreach($this->issueList as $row)
				{
				 
			?>
					<tr>
					<td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					<td>
					<?php
					$modelCategory = new Publisher_Model_DbTable_Issues();
					$parent_publication_id=$row['parent_brand_id'];
					$parent_publication_info=$modelCategory->getParentPublicationInfo($parent_publication_id);
					$categoryDetails=$modelCategory->getCategoryInfo($parent_publication_info['cat_id']);
					?>
						<a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'issues','action'=>'view','id'=>$row['id'],'parentid'=>$this->ParentPublicationInfo['id']),'',true);?>" title="View And Edit Additional Information" onclick="return goToPage(this.href,'tab2','issue');">
						<?php
						echo $row['title'];
						//$getBrandInfo=$modelCategory->getBrandInfo($row['title']);
						//echo $getBrandInfo['brand'];
						?>
						</a>
					</td> 
					
					<td>
					<?php 
					$modelGenre = new Publisher_Model_DbTable_Genres();
					$genreDetails=$modelGenre->getGenreInfo($row['product_type']);
					echo $genreDetails['genre'];
					?>
					</td>
					<td>
					<?php
						echo $categoryDetails['category_name'];
					?>
					</td> 
				    
					<td>
					<?php
					$modelEditon = new Publisher_Model_DbTable_Edition();
					$editionInfo = $modelEditon->fetchRow("id='$row[edition_id]'");
					echo $editionInfo['edition'];
					?>
					</td>
					
					<td><?php echo $row['publish_time'];?></td>
					<?php
					if(strtolower(trim($this->sessPublisherInfo->user_type))==strtolower(trim('publisher')))
					{
					?>
					  <td>
							<?php 
							if($row['status']=='1')
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'issues','action'=>'inactive','id'=>$row['id'],'parentid'=>$this->ParentPublicationInfo['id']),'',true);?>" title="Deactivate Issue" onclick="return inactive(this.href,'tab2','issue');"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>	
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'issues','action'=>'active','id'=>$row['id'],'parentid'=>$this->ParentPublicationInfo['id']),'',true);?>" title="Activate Issue" onclick="return active(this.href,'tab2','issue');"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
						    <?php	
							}
							?>
						
					   </td>
					   <?php
					   }
					   ?>
					   <td>
					   
						   <!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'issues','action'=>'edit','id'=>$row['id']),'',true);?>" title="Edit Issue" onclick="return goToPage(this.href,'tab2','issue');"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>-->
						
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'issues','action'=>'view','id'=>$row['id'],'parentid'=>$this->ParentPublicationInfo['id']),'',true);?>" title="View And Edit Additional Information" onclick="return goToPage(this.href,'tab2','issue');"><img alt="View" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/application_view_detail.png"/></a>
								
							<?php
							if(strtolower(trim($this->sessPublisherInfo->user_type))==strtolower(trim('publisher')))
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'publisher','controller'=>'issues','action'=>'delete','id'=>$row['id'],'parentid'=>$this->ParentPublicationInfo['id']),'',true);?>" title="Delete Issue" onclick="return deleteAction(this.href,'tab2','issue');"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>
							<?php
							}
							?>
							
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
				
				if($this->totalCount>$this->pageSize)
				{
					global $tab,$tab_ajax; 
					$tab=2;$tab_ajax='issue';
					
					echo '<tr><td colspan="8">&nbsp;</td></tr>';
					echo '<tr><td colspan="8"><div class="pagination">'.$this->paginationControl($this->issueList,'Sliding','pagination.phtml').'</div></td></tr>';
				}
				
			  }
			  else
			  {
				echo '<tr><td colspan="8" class="list-not-found">No issues are available. To create issue please <a href="'.$this->url(array('module'=>'publisher','controller'=>'issues','action'=>'create','parentid'=>$this->ParentPublicationInfo['id']),'',true).'" title="Create New Issue" onclick="return goToPage(this.href,\'tab2\',\'issue\');">click here</a></td></tr>';
			  }
			?> 
			 </table>
		</div>	
	</div>
</div>
