<?php
$publisherActionUrl=$this->url(array('module'=>'user','controller'=>'auth','action'=>'index'),'',true);
?>
<!--right sidebar -->
	<aside class="right_listing login"> 
		<div class="listing">
		<!-- publisher panel -->	
			<div class="login_area">
				<h3><span>Login ::</span> <!--Publisher Panel--></h3>
				<br clear="all"/>
				<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
				<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
				<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
				<form name="form-publisher-login" id="form-publisher-login" action="<?php echo $publisherActionUrl; ?>" method="post" onsubmit="return validate_login('form-publisher-login');">
				
				<div class="row">
					<label>Username<em>*</em> :</label>
					<input type="text" name="user_name" id="user_name" value="<?php if(isset($formData['user_name'])){echo $formData['user_name'];}?>" class="req" message="Please enter your username"/>
				</div>
				
				<div class="row">
					<label>Password<em>*</em> :</label>
					<input type="password" name="user_password" id="user_password" class="req" message="Please enter your password"/>
					<input type="hidden" name="user_type" id="user_type" value="2" />
				</div>
				
				<div class="row">
					<label>&nbsp;</label>
					<input type="submit" name="btnLogin" value="Login">
				</div>
				
				<div class="row">
					<label>&nbsp;</label>
					 <a href="<?php echo $this->url(array('module'=>'user','controller'=>'auth','action'=>'forgotpassword'),'',true);?>">Forgot Password?</a>&nbsp;<a href="<?php echo $this->url(array('module'=>'user','controller'=>'register','action'=>'index'),'',true);?>">Register Now</a>
				</div>
				</form>
			</div>
		</div>
	</aside>

<!--right sidebar -->
<script type="text/javascript">
function validate_login(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	
	return true;
}
</script>
