<section id="middle">

	

<!--cart section start -->

<div class="cart">
	<div class="top_heading">
    	<div class="item">Item(s)</div>
        <div class="space">&nbsp;</div>
        <div class="prices">Price</div>
        <div class="quantity">Quantity</div>
        <div class="total">Total</div>
    </div>
    
    
    <div class="cart_detail">
    	<div class="item_content">
   	    	<img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/listing_img.jpg" width="140" height="175" alt="">
            <h5>Sample3 (The Nation)</h5>
            <span><em>by</em> Debbie Macomber</span>
            <span><em>publisher</em> Evans Brothers (Nigeria Publishers) Limited</span>
            <div class="remove_bt"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/remove_botton.png" width="90" height="25" alt=""></a></div>
        </div>
        <div class="space_content">&nbsp;</div>
        <div class="prices_content">$1099.99</div>
        <div class="quantity_content">
        	<div class="quantity_count">
            	<div class="mius"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/minus_icon.png" width="15" height="15" alt=""></a></div>
                <div class="inputbox"><input type="text" value="1" /></div>
                <div class="plus"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/plus_icon.png" width="15" height="15" alt=""></a></div>
            </div>
        </div>
        <div class="total_content">$11049.99</div>
    
    </div>
    
    <div class="cart_detail">
    	<div class="item_content">
   	    	<img src="images/listing_img.jpg" width="140" height="175" alt="">
            <h5>Sample3 (The Nation)</h5>
            <span><em>by</em> Debbie Macomber</span>
            <span><em>publisher</em> Evans Brothers (Nigeria Publishers) Limited</span>
            <div class="remove_bt"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/remove_botton.png" width="90" height="25" alt=""></a></div>
        </div>
        <div class="space_content">
            <select>
            	<option>Group</option>
                <option>Group</option>
            </select>
        </div>
        <div class="prices_content">$1099.99</div>
        <div class="quantity_content">
        	<div class="quantity_count">
            	<div class="mius"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/minus_icon.png" width="15" height="15" alt=""></a></div>
                <div class="inputbox"><input type="text" value="1" /></div>
                <div class="plus"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/plus_icon.png" width="15" height="15" alt=""></a></div>
            </div>
        </div>
        <div class="total_content">$11049.99</div>
    
    </div>

</div>


<div class="countinue_bt"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/countinue_shopping_bt.png" width="274" height="49" alt=""></a></div>

<div class="shipping_total">
	<div class="row">
    	<div class="lt">Total</div>
        <div class="rt">$22099.98</div>
    </div>
    
    <div class="row">
    	<div class="lt">Shipping</div>
        <div class="rt">$00.00</div>
    </div>
    
    <div class="row" style="border:none;">
    	<div class="lt">Tax</div>
        <div class="rt">$14.00</div>
    </div>
    
    <div class="row subtotal">
    	<div class="lt">Subtotal</div>
        <div class="rt">$22123.98</div>
    </div>
    
    <div class="row" style="border:none;"><a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/checkout_bt.png" width="274" height="49" alt=""></a></div>
</div>


<!--cart section start end -->


</section>