<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'index'),'',true);

$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Constant Management</h3></div>
	<div class="content-box-content">
	
		<div>
			<div class="action-header">
				<span class="action-title">Edit Constant</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br  clear="all"/>
			<br  clear="all"/>
			
			<form id="form-edit-constant" method="post" onsubmit="return validate_edit_constant('form-edit-constant');">
					
			<table class="table-form" cellpadding="0" cellspacing="0">
				
				<tr>
					<td width="20%" class="tdrightBold">Constant Label<span class="required">*</span> : </td>
					<td>
					   <input type="text" name="constant_label" id="constant_label" value="<?php if(isset($formData['constant_label']))echo$formData['constant_label'];?>" class="req" message="Please enter constant label" />
					   
					   <?php if(array_key_exists('constant_label',$formErrors)){echo '<div class="inline-error">'.$formErrors['constant_label'].'</div>';}?>
					</td>
				</tr>
				
				<tr>
					<td width="20%" class="tdrightBold">Constant Name<span class="required">*</span> : </td>
					<td>
					   <input type="text" name="site_constant" id="site_constant" value="<?php if(isset($formData['site_constant']))echo$formData['site_constant'];?>" class="req" message="Please enter constant name" />
					   
					   <?php if(array_key_exists('site_constant',$formErrors)){echo '<div class="inline-error">'.$formErrors['site_constant'].'</div>';}?>
					</td>
				</tr>
				
				<tr>
					<td width="20%" class="tdrightBold">Constant Value<span class="required">*</span> : </td>
					<td>
					   <input type="text" name="constant_value" id="constant_value" value="<?php if(isset($formData['constant_value']))echo$formData['constant_value'];?>" class="req" message="Please enter constant value" />
					   
					   <?php if(array_key_exists('constant_value',$formErrors)){echo '<div class="inline-error">'.$formErrors['constant_value'].'</div>';}?>
					</td>
				</tr>
				
				<tr>
					<td width="20%" class="tdrightBold">&nbsp;</td>
					<td>
						<input type="submit" value="Update" class="button-Add"/>
						<input type="button" value="Cancel" class="button-cancel" onclick="window.location.href='<?php echo $cancelUrl;?>';"/>
					</td>
				</tr>
			  
			 </table>
		 </form>
	</div>
</div>
<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">
function validate_edit_constant(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>
