<?php
$cancelUrl=$this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'index'),'',true);
$backUrl=$this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'index'),'',true);

$formData=(isset($this->formData))?$this->formData:array();
$formErrors=(isset($this->formErrors))?$this->formErrors:array();

?>
<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Api Key Management</h3></div>
	<div class="content-box-content">
	
		<div>
			<div class="action-header">
				<span class="action-title">Generate New Api Key</span>
				<ul class="horizonal-menu">
					<li class="back"><a href="<?php echo $backUrl;?>">Back</a></li>
				</ul>
			</div>
			
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br  clear="all"/>
			<br  clear="all"/>
			
			<form id="form-apikey" method="post" onsubmit="return validate_apikey('form-apikey');">
					
			<table class="table-form" cellpadding="0" cellspacing="0">
				<tr>
					<td width="20%" class="tdrightBold">Api key Length<span class="required">*</span> : </td>
					<td>
					   <input type="text" name="apikeylength" id="apikeylength" value="<?php if(isset($formData['apikeylength']))echo$formData['apikeylength'];?>" class="req number" message="Please enter key length" invalidmessage="Enter numeric value only." />
					   <?php if(array_key_exists('apikeylength',$formErrors)){echo '<div class="inline-error">'.$formErrors['apikeylength'].'</div>';}?>
					</td>
				</tr>
				
				<tr>
					<td width="20%" class="tdrightBold">&nbsp;</td>
					<td>
						<input type="submit" value="Generate" class="button-Add"/>
						<input type="button" value="Cancel" class="button-cancel" onclick="window.location.href='<?php echo $cancelUrl;?>';"/>
					</td>
				</tr>
			  
			 </table>
		 </form>
		 
		 <br  clear="all"/>
		 <br  clear="all"/>
		 <table class="table-list" cellpadding="0" cellspacing="0">
				
				<tr>
				   <th width="10%">SL.No</th>
				   <th width="30%">Api Key</th>
				   <th width="30%">Key Type</th>
				</tr>
				
				<?php
				if(isset($this->apikeyList) && count($this->apikeyList)>0)
				{
					$sNumber=1;
					foreach($this->apikeyList as $row)
					{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo $row->apikey;?></td>
					   <td><?php echo $row->key_type;?></td>		   
					</tr>
			<?php
					$sNumber++;
					}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="9">&nbsp;</td></tr>';
						echo '<tr><td colspan="9"><div class="pagination">'.$this->paginationControl($this->apikeyList,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="9" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			</table>
	</div>
</div>
<?php /************JAVASCRIPT CODE**************/?>
<script type="text/javascript">
function validate_apikey(pFormId)
{
	if(pFormId)
	{
		if(!common_validation(pFormId))
		{
			return false;
		}
	}
	return true;
}
</script>
