<div class="content-box">
	<div class="content-box-header"><h3 style="cursor: s-resize;">Notifications</h3></div>
	<div class="content-box-content">
	
		<div>
		 
			<br style="clear: both;"/>
			<?php if(isset($this->messages)){for($i=0;$i<count($this->messages);$i++){echo $this->messages[$i];}}?>
			<?php if(isset($this->successMessage)){echo $this->successMessage;}?>
			<?php if(isset($this->errorMessage)){echo $this->errorMessage;}?>
			
			<br style="clear: both;"/>	
			<br style="clear: both;"/>	
			
			<table class="table-list" cellpadding="0" cellspacing="0">
			
			   <tr>
				   <th width="10%">SL.No</th>
				   <th width="30%">Notification Type</th>
				   <th width="20%">Title</th>
				  <th width="10%">Message</th>
				   <th width="10%">Status</th>				  
				   <th width="10%">Action</th>
			   </tr>
			   
			<?php 
			  if(isset($this->notificationsdata) && count($this->notificationsdata)>0)
			  {
				$sNumber=1;
				foreach($this->notificationsdata as $row)
				{
			?>
					<tr>
					   <td><?php echo ($sNumber+($this->page-1)*$this->pageSize);?></td>
					   <td><?php echo stripslashes($row->ntype);?></td> 
					   <td><?php echo stripslashes($row->title);?></td>
					   <td><?php echo stripslashes($row->message_body);?></td>
					   <td>
						
							<?php 
							 if($row->status=='1')
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'ninactive','id'=>$row->nid),'',true);?>"><img alt="Active" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/active.png"/></a>
							<?php  
							}
							else
							{
							?>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'nactive','id'=>$row->nid),'',true);?>"><img alt="Inactive" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/inactive.png"/></a>
							<?php  
							}
							 
							?>
						
					   </td> 
					   <td>
							<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'nedit','id'=>$row->nid),'',true);?>"><img alt="Edit" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/icon_edit.png"/></a>
							
							<!--<a class="action-icon" href="<?php echo $this->url(array('module'=>'admin','controller'=>'sitesettings','action'=>'delete','id'=>$row->nid),'',true);?>" onclick="return confirm('Are you sure to delete?');"><img alt="Delete" src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/images/trash.gif"/></a>-->
					   </td>
				   </tr>
			<?php
					$sNumber++;
				}
					if($this->totalCount>$this->pageSize)
					{
						echo '<tr><td colspan="9">&nbsp;</td></tr>';
						echo '<tr><td colspan="9"><div class="pagination">'.$this->paginationControl($this->notificationsdata,'Sliding','pagination.phtml').'</div></td></tr>';
					}
			  }
			  else
			  {
				echo '<tr><td colspan="9" class="list-not-found">Data Not Found</td></tr>';
			  }
			?> 
			 </table>
		</div>

	</div>
</div>