<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle('Electronic Vendor Ltd::Admin')?>
<?php echo $this->headMeta()?>
<?php echo $this->headLink()?>
<?php echo $this->headStyle()?>
<?php echo $this->headScript()?>

<!------------------------  New Admin Code  -------------------------------->

<link href="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/invalid.css" media="screen" rel="stylesheet" type="text/css"/>

<link href="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/reset.css" media="screen" rel="stylesheet" type="text/css"/>

<link href="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/style.css" media="screen" rel="stylesheet" type="text/css"/>

<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/facebox.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/jquery-1.3.2.min.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/jquery.date.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/jquery.datePicker.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/jquery.wysiwyg.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/simpla.jquery.configuration.js"></script>


<link href="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/admin/admin_styles.css" media="screen" rel="stylesheet" type="text/css"/>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/jquery-v1.7.1.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/admin/common_validation.js"></script>

</head>


<body>
<div id="body-wrapper">
<div>
	
	<div>
		<?php echo $this->layout()->content;?>
	</div>
	
</div>
</div>
</body>
</html>