<?php echo $this->doctype(); ?>
<html>
<head>
<?php echo $this->headTitle('Electronic Vendor');?>


<?php
$currenturl= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
$posa = strpos($currenturl, "about-us");  
$posb = strpos($currenturl, "faqs"); 
$posc = strpos($currenturl, "contact-us");
$pageModel=new Model_DbTable_Page();

if($posa) 
{
 $metaInfo=$pageModel->getInfoById("1");  
?>
<meta name="title" content="<?php echo stripslashes($metaInfo['meta_title']);  ?>">
<meta name="keywords" content="<?php echo stripslashes($metaInfo['meta_keywords']); ?>">
<meta name="description" content="<?php echo stripslashes($metaInfo['meta_description']); ?>">	
<?php
}

if($posb) 
{
 $metaInfo=$pageModel->getInfoById("5");  
?>
<meta name="title" content="<?php echo stripslashes($metaInfo['meta_title']);  ?>">
<meta name="keywords" content="<?php echo stripslashes($metaInfo['meta_keywords']); ?>">
<meta name="description" content="<?php echo stripslashes($metaInfo['meta_description']); ?>">	
<?php
}

if($posc) 
{
 $metaInfo=$pageModel->getInfoById("7");  
?>
<meta name="title" content="<?php echo stripslashes($metaInfo['meta_title']);  ?>">
<meta name="keywords" content="<?php echo stripslashes($metaInfo['meta_keywords']); ?>">
<meta name="description" content="<?php echo stripslashes($metaInfo['meta_description']); ?>">	
<?php
}
?>





<?php
/********************************* Head Meta **************************/
//$this->headMeta()->appendHttpEquiv('X-UA-Compatible',"IE=edge,chrome=1");
//$this->headMeta()->setCharset('UTF-8');
//$this->headMeta()->appendName("viewport", "width=device-width,initial-scale=1.0");
echo $this->headMeta();
/********************************* Head Meta Ends Here**************************/

/********************************* Head Css **************************/
$this->headLink()->appendStylesheet($this->serverUrl().$this->baseUrl().'/public/css/default/css/style.css');
$this->headLink()->appendStylesheet($this->serverUrl().$this->baseUrl().'/public/css/default/css/skin.css');
//$this->headLink()->appendStylesheet($this->serverUrl().$this->baseUrl().'/public/css/default/banner-slider/slidy.css');

$this->headLink()->appendStylesheet($this->serverUrl().$this->baseUrl().'/public/css/default/css/flexslider.css');
$this->headLink()->appendStylesheet($this->serverUrl().$this->baseUrl().'/public/css/default/css/rating.css');
$this->headLink()->appendStylesheet($this->serverUrl().$this->baseUrl().'/public/css/default/css/colorbox.css');


echo $this->headLink();
/******* Inline Css **********/
echo $this->headStyle();
/******* Inline Css **********/
/********************************* Head Css Ends Here **************************/

/********************************* Head Script **************************/
$this->headScript()->prependFile($this->serverUrl().$this->baseUrl().'/public/css/default/js/jquery.min.js');

$this->headScript()->appendFile($this->serverUrl().$this->baseUrl().'/public/js/default/common_validation.js');

$this->headScript()->appendFile($this->serverUrl().$this->baseUrl().'/public/css/default/js/jquery.js');

//$this->headScript()->appendFile($this->serverUrl().$this->baseUrl().'/public/css/default/banner-slider/slidy.js');

$this->headScript()->appendFile($this->serverUrl().$this->baseUrl().'/public/css/default/js/jquery.flexslider.js');
$this->headScript()->appendFile($this->serverUrl().$this->baseUrl().'/public/css/default/js/jquery.colorbox.js');


echo $this->headScript();
/********************************* Head Script Ends Here **************************/

$controller_name = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action_name = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

//echo "controller name".$controller_name;
//echo "action name".$action_name;

?>

<script type="text/javascript">
function clearText(field){
if (field.defaultValue == field.value) field.value = '';
else if (field.value == '') field.value = field.defaultValue;
}
</script>
	<!--[if IE]>
            <script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/js/html5.js" type="text/javascript"></script>
        <![endif]-->

		
	<!-- tabing -->
	<script type="text/javascript">
            $(document).ready(function(){
                 //tabing hide show
                $("[id^=link]").click(function(){
                    idArr = this.id.split("_");
                    $("[id^=link]").removeClass("active");
                    $("#link_" + idArr[1]).addClass("active");

                    $("[id^=conetnt2_]").hide();
                    $("#conetnt2_" + idArr[1]).show();
                });
			});
        
	/*if(window.sessionStorage.getItem('name'))
	{
		alert(window.sessionStorage.getItem('name'));
	}
	else
	{
		window.sessionStorage.setItem('name', "jai")
	}
	*/
	</script>
    
    <script>
			$(document).ready(function(){
				//Examples of how to assign the Colorbox event to elements
				$(".inline").colorbox({inline:true, width:"30%"});
				//Example of preserving a JavaScript event for inline calls.
				$("#click").click(function(){ 
					$('#click').css({"background-color":"#f00", "color":"#fff", "cursor":"inherit"}).text("Open this window again and this message will still be here.");
					return false;
				});
			});
		</script>
    
<script language="javascript" type="text/javascript">
function searchsubmit()
{
	var searchval = document.getElementById('search_box').value;
	 
	window.location.href = '<?php echo $this->serverUrl().$this->baseUrl();?>/search/index/val/'+searchval;
}
</script>
	
 <script type="text/javascript">
jQuery(document).ready(function() {
	jQuery('.more_cate').click(function() {
	jQuery('#hide_link').slideToggle('slow')
	});
	
	jQuery('.more_magazine').click(function() {
	jQuery('#hide_magazine').slideToggle('slow')
	});
	
	jQuery('.more_ebook').click(function() {
	jQuery('#hide_ebook').slideToggle('slow')
	});
});
</script>

		
</head>

<body>
<div id="container">
<!--Header part -->
<header id="heder">
<div class="logo"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'',true);?>"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/logo.png" alt=""></a></div>

<div class="head_right">

<!--Toplink -->
<div class="toplink">
<?php

?>
<div class="tolltip"><?php if(isset($this->storeName) && !empty($this->storeName))echo $this->storeName;?><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/w_arrow.png" alt="">

<div class="tolltip_main">
<div class="tolltip_content">
<span class="arrow">&nbsp;</span><br>

<p class="heading">Find us in Africa</p>
<ul>
<?php

if(!empty($this->allStored) && count($this->allStored)>0)
{
    $modelContinent= new Admin_Model_DbTable_Continents();
	
	$modelBooks = new Publisher_Model_DbTable_Books();
	
	
	
	foreach($this->allStored as $continent_id=>$country_array)
	{
		$continentInfo=$modelContinent->fetchRow("id='$continent_id'");
		?>
		<?php //echo $continentInfo->continent;?>
        
		<?php
		$storect=0;
		foreach($country_array as $cid=>$cname)
		{
			$publicationcount = $modelBooks->getPublicationListByStore($cid,1);	
			$countryFlag = $modelBooks->getCountryName($cid);		 
	        $storect++;
			if(count($publicationcount)>0)
			{
			?>
            	 <li>
					<div class="countryalign">
                 <?php
				if($countryFlag['country_flag']!='')
				{
				?>
               
					<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/auth/storechange/storeid/<?php echo $cid; ?>"><img src='<?php echo $this->serverUrl().$this->baseUrl().'/public/uploads/users/'.$countryFlag['country_flag']?>' width="30" height="20"></a>
				<?php					
				}
			?>
			<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/auth/storechange/storeid/<?php echo $cid; ?>"><?php echo $cname; ?></a>
					</div>
				</li>
			<?php
			
			
			if($storect!=count($country_array))
			echo "";
			}
		}
		?>
		<?php
	}

}
?>
</ul>
</div>
</div>


</div>  |  
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/help" <?php if($this->currentController=='page' && $this->currentTitle=='Help') echo $this->class_active;?>>Help</a>  |  
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/sitemap" <?php if($this->currentController=='page' && $this->currentTitle=='Sitemap') echo $this->class_active;?>>Sitemap</a>  | 
 
<?php

if(isset($this->sessPublisherInfo) && $this->sessPublisherInfo!=null)
{
?>
Hi, <a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'index','action'=>'index'),'',true);?>"><?php echo $this->sessPublisherInfo->first_name;?></a> | <a href="<?php echo $this->serverUrl().$this->baseUrl();?>/publisher/auth/logout/">Logout</a> |
<?php
}
elseif(isset($this->sessCompanyInfo) && $this->sessCompanyInfo!=null)
{
?>
Hi, <a href="<?php echo $this->url(array('module'=>'company','controller'=>'index','action'=>'index'),'',true);?>"><?php echo $this->sessCompanyInfo->first_name;?></a> | <a href="<?php echo $this->serverUrl().$this->baseUrl();?>/company/auth/logout/">Logout</a> |
<?php
}
elseif(isset($this->sessUserInfo) && $this->sessUserInfo!=null)
{
?>
Hi, <a href="<?php echo $this->url(array('module'=>'user','controller'=>'index','action'=>'index'),'',true);?>"><?php echo $this->sessUserInfo->first_name;?></a> | <a href="<?php echo $this->serverUrl().$this->baseUrl();?>/user/auth/logout/">Logout</a> |
<?php
}
else
{
?>

<div class="tolltip">Register<img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/w_arrow.png" alt="">

<div class="tolltip_main" style="width:280px;">
<div class="tolltip_content">
<span class="arrow">&nbsp;</span>
<p>Sign up for <a href="<?php echo $this->serverUrl().$this->baseUrl().'/company/register/';?>">Company</a>/<a href="<?php echo $this->serverUrl().$this->baseUrl().'/publisher/register/';?>">Publisher</a>/<a href="<?php echo $this->serverUrl().$this->baseUrl().'/user/register/';?>">User</a></p>
  
</div>
</div>


</div>  



<div class="tolltip">Sign In<img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/w_arrow.png" alt="">

<div class="tolltip_main" style="width:280px;">
<div class="tolltip_content">
<span class="arrow">&nbsp;</span>
 <p>Sign In as a <a href="<?php echo $this->serverUrl().$this->baseUrl().'/company/auth/';?>">Company</a>/<a href="<?php echo $this->serverUrl().$this->baseUrl().'/publisher/auth/';?>">Publisher</a>/<a href="<?php echo $this->serverUrl().$this->baseUrl().'/user/auth/';?>">User</a></p>
</div>
</div>


</div> 

<?php	
}
?>
<span class="share_icons">Follow us on : 
<a href="https://twitter.com/eVendor_Reader" target="_blank"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/twitter_icon.png" alt=""></a> 
<a href="https://facebook.com/evendor" target="_blank"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/facebook_icon.png" alt=""></a> 
<!--<a href="#"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/vion_icon.png" alt=""></a>--> 
<a href="<?php echo $this->serverUrl().$this->baseUrl().'/rssfeed.xml';?>" target="_blank"><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/rss_icon.png" alt=""></a>
</span>
</div>
<!--Toplink -->


</div>

<div class="head_right">
<!--Topmenu -->
<div class="topmenu">
<ul>
<li>
<a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'',true);?>" <?php if($this->currentController=='index') echo$this->class_active;?>>Home</a>
</li>

<li>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/about-us" <?php if($this->currentController=='page' && $this->currentTitle=='about-us') echo $this->class_active;?>>About us</a>
</li>

<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/catalogue/" <?php if($this->currentController=='catalogue') echo $this->class_active;?>>Catalogue</a></li>
<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/reader">Readers</a></li>
<?php
if(isset($this->sessPublisherInfo) && $this->sessPublisherInfo!=null)
{
?>
<li>
<a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'index','action'=>'index'),'',true);?>">Publisher/Author</a>
</li>
<?php
}
elseif(isset($this->sessCompanyInfo) && $this->sessCompanyInfo!=null)
{
?>
<li>
<a href="<?php echo $this->url(array('module'=>'company','controller'=>'index','action'=>'index'),'',true);?>">Company Panel</a>
</li>
<?php
}
elseif(isset($this->sessUserInfo) && $this->sessUserInfo!=null)
{
?>
	<li>
<a href="<?php echo $this->url(array('module'=>'user','controller'=>'index','action'=>'index'),'',true);?>">User Panel</a>
</li>
<?php
}
else
{
?>
<li>
<!--<a href="<?php echo $this->url(array('module'=>'default','controller'=>'login','action'=>'index'),'',true);?>">Publisher/Author</a>-->
<a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'auth','action'=>'index'),'',true);?>">Publisher/Author</a>
</li>

<li>
<a href="<?php echo $this->url(array('module'=>'company','controller'=>'auth','action'=>'index'),'',true);?>">Company</a>
</li>
<?php
}

?>

<!--<li><a href="#">Authors</a></li>-->
<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/contact-us" <?php if($this->currentController=='page' && $this->currentTitle=='contact-us') echo$this->class_active;?>>Contact us</a></li>
<li><a href="<?php echo $this->serverUrl().$this->baseUrl();?>/faqs" <?php if($this->currentController=='faqs') echo$this->class_active;?>>FAQS</a></li>
</ul>
</div>

<!--Topmenu -->
</div>

<!--Magazine link -->
<nav>
<div id="breadcrumb">
<?php
if($this->currentController=='page')
{
	echo"<a href='".$this->serverUrl().$this->baseUrl()."'>Home</a> > ".$this->pageInfo->title;	
}
else
{
echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
}
?>
</div>

<?php
$currenturl=$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
$currenturl=explode("/",$currenturl);

if(in_array('contact-us',$currenturl))
{
    // contactus page
}
else
{
	$tempObj = new Model_DbTable_Checkout();  
	$storage_company = new Zend_Auth_Storage_Session('company_type');
	$company_data = $storage_company->read();
	if(count($company_data)>0)
	{
		$user_id_comment = $company_data->id;	
		$user_type = "1";
		$user_sess_inf = '1';
	}
	$storage_user = new Zend_Auth_Storage_Session('account_type');
	$data_user = $storage_user->read();
	if(count($data_user)>0)
	{
		$user_id_comment = $data_user->id;	
		$user_type = "2";
		$user_sess_inf = '1';
	}
	$sessionid = session_id();
	$getTempData = $tempObj->fetchAll("user_id='".$user_id_comment."' and session_id='".$sessionid."'");
?>

<ul>
 <li class="shopping-cart">
 <?php
 if(count($getTempData)>0)
 {
 ?>
 <a href="<?php echo $this->serverUrl().$this->baseUrl()?>/checkout/cart/" >SHOPPING CART</a>
 <?php
 }
 else
 {
 ?>SHOPPING CART
 <?php
 }
 ?> 
 </li>
<li class="search">
<?php
//$searchUrl=$this->url(array('module'=>'default','controller'=>'search','action'=>'index'),'',true);
$searchkey = "";
$storSearchId='';
$searchUrl=$this->serverUrl().$this->baseUrl().'/search/storeinsession';

$postkeyword = new Zend_Session_Namespace('searchkeyword');
$searchkey = $postkeyword->searchword;
$storSearchId = $this->storSearchId;
?>
<span id="err_search" style="display:none; float:right;"></span>
<form id="form-add-book" method="post" action="<?php echo $searchUrl;?>" onSubmit="return validSearchForm();">
Search <input type="text" name="search_box" id="search_box" value="<?php if($searchkey!='' && $this->currentController=='search'){ echo $searchkey; } else { ?>Enter search here<?php } ?>" onBlur="if (this.value == '') this.value = 'Enter search here';" onFocus="if (this.value == 'Enter search here') this.value = '';"/>
<select name="country_id" id="country_id" >
	<option value="all">All</option>
	<option value="<?php echo '248';?>" <?php if($storSearchId == '248'){?>selected<?php }?> >International Store</option>
<?php 
$allstore = $this->allStored[6];
if(count($this->allStored)>0)
{
	foreach($allstore as $key=>$val)
	{
	?>
		<option value="<?php echo $key;?>" <?php if($storSearchId == $key){?>selected<?php }?> ><?php echo $val;?></option>
	<?php
	}
}
?>
	</select>
 <input type="submit" value="GO!" name="btn_search" id="btn_search" /></form></li>

</ul>
<?php
}
?>
</nav>
<!--Magazine link -->

</header>
<!--Header part -->

<!--Middle Section -->
<section id="middle" <?php if($controller_name=='index') { ?>class="gap" <?php } ?>>

<?php 

echo $this->layout()->content;?>

</section>
<!--Middle Section -->


<!--Footer section-->
<footer>
<div class="visa"><span>Service Provided by Unified Payments Services Limited</span><img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/visa.png" alt=""> <img src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/default/images/master.png" alt=""></div>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>" class="first_link">Home</a>        
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/about-us">About us</a>

<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/catalogue/" <?php if($this->currentController=='catalogue') echo $this->class_active;?>>Catalogue</a>
<a href="#">Readers</a>
<?php
if(isset($this->sessPublisherInfo) && $this->sessPublisherInfo!=null)
{
?>
<a href="<?php echo $this->url(array('module'=>'publisher','controller'=>'index','action'=>'index'),'',true);?>">Publisher/Author</a>
<?php
}
elseif(isset($this->sessCompanyInfo) && $this->sessCompanyInfo!=null)
{
?>
<a href="<?php echo $this->url(array('module'=>'company','controller'=>'index','action'=>'index'),'',true);?>">Company Panel</a>
<?php
}
else
{
?>
<a href="<?php echo $this->url(array('module'=>'default','controller'=>'login','action'=>'index'),'',true);?>">Publisher/Author</a>
<?php
}
?>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/contact-us">Contact us</a>

<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/faqs" <?php if($this->currentController=='faqs') echo$this->class_active;?>>FAQS</a>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/terms-and-conditions">Terms & Conditions</a>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/customer-service">Customer Service</a>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/privacy-policy">Privacy Policy</a>
<a href="<?php echo $this->serverUrl().$this->baseUrl();?>/page/index/title/delivery-cancellation-policy">Return/Delivery/Cancellation Policy</a>
<br>
&copy; Copyright <?php echo date("Y");?>. All Rights Reserved By Electronic Vendor Ltd.
</footer>
<!--Footer section-->

<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 

  ga('create', 'UA-49186764-1', 'evendornigeria.com');

  ga('send', 'pageview');

 

</script>


</div>

</body>
</html>
<script type="text/javascript">
function validSearchForm()
{
	search_box = document.getElementById("search_box").value;
	
	if(search_box == 'Enter search here' || search_box=='')
	{
		$("#err_search").html("<font color='red' >Please enter search keyword.</font>");
		$("#err_search").show();
		$("#err_search").fadeOut(4000);
		return false;
	}
	

}
</script>
