<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle('Electronic Vendor Ltd')?>
<?php echo $this->headMeta()?>
<?php echo $this->headLink()?>
<?php echo $this->headStyle()?>
<?php echo $this->headScript()?>
<link href="<?php echo $this->serverUrl().$this->baseUrl();?>/public/css/company/company_styles.css" media="screen" rel="stylesheet" type="text/css"/>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/company/jquery-v1.7.1.js"></script>
<script src="<?php echo $this->serverUrl().$this->baseUrl();?>/public/js/company/common_validation.js"></script>
</head>
<body>
<div class="main" id="main">
	<div id="header">
	<div class="logo"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'',true);?>">Electronic Vendor Ltd</a></div>
	</div>
	
	<div class="middle" id="middle">
		<?php echo $this->layout()->content;?>
	</div>

</div>
</body>
</html>